### ISSUE TITLE
Show all currencies in the homescreen

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#179]
It could be great if community/account tab could be hidden to get more height space.
If there is one account, display community and account name in the title or bottom bar.
If there is many accounts, a switcher between accounts could give more space on screen, such as referential switcher. This switcher could be placed on the bottom bar.

**Comment by Insoleet** [comment]
Something need to be done about this yes.

**Comment by M5oul** [comment]
**Update since UI refactoring:**

If there is one account, display community and account name in the title or bottom bar.
If there is many accounts, a switcher between accounts could give more space on screen, such as referential switcher. This switcher could be placed on the bottom bar.

**Comment by Insoleet** [comment]
In next versions, we will show all currencies added my all accounts in the homescreen.

**Comment by M5oul** [comment]
This ticket make no sense now with new interface and management of accounts and currencies.
