### ISSUE TITLE
Add a parameter for key generation

### ISSUE THREAD

**Issue by Insoleet** [duniter/sakia#197]
As cgeek explained on the forum, it would be great if we could choose key generation parameters.

> For example, we could imagine that N=4096, r=16, p=1 may be named "Default generation". We could imagine also to have another set named "Strengthen generation" with N=16384, r=32, p=1. And why not a "Manual generation" where the user can choose manually its parameters.

I think this should be available only if the expert mode is enabled.

**Comment by c-geek** [comment]
I reopen since it seems I cannot select my Nrp parameters.
