### ISSUE TITLE
Transactions: it is hard to differenciate the order of units

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#212]
I can see in my transactions list some units of order (a power of 10), for example `UD`, `cUD`, `pUD`, etc. I like the idea, but I feel it hard to read:

![image](https://cloud.githubusercontent.com/assets/969136/9957922/c39f8244-5e04-11e5-9a1c-0635010f55a9.png)

Wouldn't it be good to also have colors to signify the order? Like for Euros: we know that yellow coins means `[0,10 ; 0,50]` and bronze means `[0,01 ; 0,05]`.

The colors could always be the same, and shift when another power of 10 is reached by the UD.

What do you think?

**Comment by Insoleet** [comment]
Interesting idea ! 

We need to think about it a bit more about the display, but definitely interesting. Won't be out for 0.11.

You can always disable "scientific units" in your preferences to go back to the old display.

**Comment by Insoleet** [comment]
No more problem since 0.30 release.
