### ISSUE TITLE
Implement a view to suggest missing conditions to be member

### ISSUE THREAD

**Issue by Insoleet** [duniter/sakia#227]
With the new feature of ucoin nodes, cutecoin should be able to suggest identities to contact to become a member.

http://forum.ucoin.io/t/new-feature-better-know-the-requirements-to-join/465

**Comment by M5oul** [comment]
Certifications and distance with the whole community are two conditions to be a member.

**Comment by Insoleet** [comment]
This feature will be postponed. We need to see how the new wot rules goes before implementing such a view.

**Comment by Insoleet** [comment]
Finally implemented in 0.20.0dev9.
