### ISSUE TITLE
Display each endpoint as a different peer under Network tab

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#265]
Sakia keep one node with the same uid. Other are not displayed.

**Comment by M5oul** [comment]
Linked to https://github.com/duniter/duniter/issues/219.

**Comment by M5oul** [comment]
Now this feature is available on duniter nodes.
It would be great to have this feature.

**Comment by Insoleet** [comment]
Sakia is able to do it natively. The Peer document will contain multiple BMA entries. Sakia will choose the first one in the list.
The feature should be that should be able to handle multiple BMA endpoints on one node.

**Comment by M5oul** [comment]
What I pushed on a new branch doesn't works.

**Comment by Insoleet** [comment]
Yes, the problem is something else. Sakia needs to be able to handle multiple endpoints for one pubkey. So, Sakia still needs to identify nodes by pubkey, but it should be able to handle all BMA endpoints of a node.

At the moment we handle only one endpoint (the first one found in the list, see https://github.com/duniter/sakia/blob/master/src/sakia/core/net/node.py#L239 )

**Comment by M5oul** [comment]
@c-geek said:

Now that having multiple peers per pubkey on the network is possible, it would be nice if Sakia could display these peers as independant peers under the Network tab.

For example this peer:

```json
{
  "version": 2,
  "currency": "test_net",
  "endpoints": [
    "BASIC_MERKLED_API cgeek.fr 88.174.120.187 2a01:e35:8ae7:8bb0:b468:a0c:a607:379f 9330",
    "BASIC_MERKLED_API win-dev.cgeek.fr 88.174.120.187 9333"
  ],
  "block": "38706-0000157811BF9B2A6A3C708C34F27A24FAD4ABB62B71D1309758E6D967040750",
  "signature": "g6ZcBv+HtIBBlP9jBP37CLMpj41NR8F6Snng/z6hwOrQWfowG+cIbHw30+vTcJJlaWzETucNdyGiSFFNlM9fAw==",
  "pubkey": "HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk"
}
```

is currently displayed as only 1 peer, which is `cgeek.fr`. It would be cool to also see `win-dev.cgeek.fr` independently.
