### ISSUE TITLE
New profile logic

### ISSUE THREAD

**Issue by Insoleet** [duniter/sakia#295]
We should replace `Account` by a `Profile` with the following points : 
- A profile is named and has multiple properties : 
  - Multiple identities - each one linked to a community
  - Multiple wallets - those are not identities, they don't need a UID

This will need a big refactoring and thus will be need to be changed before anything else.

**Comment by vtexier** [comment]
It is a critical enhancement indeed !

uCoin apps showed us that it is more convenient to choose a community first, then swap rapidly between wallets (with uid or not...).

So in Sakia, I saw the hierarchical organisation like that : 

Profile -> communities (moneys) -> uid -------->wallet
                                                     -> wallet

Community/money is the same for me so why your wallets without uid are not linked to a community/money ?

**Comment by Insoleet** [comment]
I think Wallets could be totally decolorated from any Community, meaning they would be available in every community added. A wallet could be linked to multiple communities then ?

But maybe, from a user point of view, this doesn't makes sense ?

**Comment by Insoleet** [comment]
I thank again about it. It's not a core problem and it's more about the UI. 
I think in the core, we can still have, whatever the UI : 
```
Account -> | Communities
           | Wallets
```

For the UI, what should change is the following : 
 - The main view should show any community linked to any account
 - Adding an account should just ask for the UID/Salt/password. No more communities management by account.
 - Adding a community should ask "Which Identity do you want to use ?" with a combobox and a "+" button to be able to create a new account.
 - Adding a wallet, I'm not sure. In the "configure a community" view, or like the community, with a button "which identity to you want to use ?"

**Comment by c-geek** [comment]
May I suggest 2 things:

##### Vocabulary
Wouldn't it be better to use *Currency* instead of *Community*? Because for uCoin clients, a _Community_ is always identified by a _Currency_ name.

##### Your first idea
I prefer your first idea to the other, but I wonder if it wouldn't be better *not to ask* "which identity to use" to connect to a currency if we have only one identity for our account. I know it is possible to handle multiple identities, but the usual case is to have only 1 identity for all currencies. Proposing to use another identity will encourage people to have multiple identities, and IMHO this is not wisheable.

So maybe this question could be displayed only for a given account carrying only 1 identity, and Sakia could propose a UI to manage the account and add/remove identities in it if we want to have multiple identities.

What do you think about it?

**Comment by Insoleet** [comment]
> I prefer your first idea to the other, but I wonder if it wouldn't be better not to ask "which identity to use" to connect to a currency if we have only one identity for our account.

I agree with you on this point. This is why I chose the current UI, with the creation of one account, and the usage of multiple currencies under this one account.
But from the feedback I had during FMML6, I felt like it was not the good way to do it. But maybe I'm wrong ?

**Comment by galuel** [comment]
Choosing a money is a very heavy choice for years. I don't think this question is a key features to be done quickly. Without doubts there are key features to be developped much more important like : 

Graphical bars to compare one's amount of money compared to M/N

Graphical bars to compare money to be sent, or money received, compared to current amount of money.

**Comment by Insoleet** [comment]
@galuel please open another issue for this point

For the Profiles, after discussing with vit yesterday, here is what I'm gonna do : 

 - Profile : A default profile is available, and multiple profiles can be set up
 - A profile needs a first Account. It is possible after setting the profile to add more Accounts if needed.
 - A profile can set up wallets, in addition to wallets created via identities
 - Each Account has multiple communities

In the UI, I see the following organisation : 

- The user choose a profile and can switch between profiles
- In a window `Configuration`, a user can : 
  - Add communities : the dialog here would use by default the profile identity, and a `+` button could be available to add/chose another identity
 - Configure wallets : Here the user can configure wallets created via identities creation. He can also add and remove wallets not linked to identities.
 - Configure Identities : Here the user could check up his created identities and their parameters. 

I'll try to design the UI I imagine for this.

**Comment by vtexier** [comment]
What is an "account" here?

**Comment by Insoleet** [comment]
A user identity like today account.

**Comment by Insoleet** [comment]
Here is the view I imagine : 

![screenshot_20160731_132221](https://cloud.githubusercontent.com/assets/1170293/17276193/d7c63a80-5721-11e6-8e1a-3942a3c7da42.png)


What do you think about it ?

**Comment by vtexier** [comment]
Yes it is very clear.
But my concern is about quickly switching between accounts in the same money. 
May be you can add account level under each money to the tree.

**Comment by Insoleet** [comment]
Or I could simply add the same money twice for two different accounts ? Maybe from a user point of view it is easier to understand ?

**Comment by vtexier** [comment]
Yes we can :)
