### ISSUE TITLE
Remember selection of Unit, when restarting sakia

### ISSUE THREAD

**Issue by samuelandert** [duniter/sakia#320]
When restarting the saki client and being on the UD Unit, it will automatically jump back to the Quantative unit

**Comment by M5oul** [comment]
You can configure default referential in configuration.

**Comment by Samsemilio** [comment]
Where to find the config file?

**Comment by Insoleet** [comment]
File > parameters

**Comment by Samsemilio** [comment]
On mac there is only import and export options in the file menu:
![bildschirmfoto 2015-12-27 um 13 30 38](https://cloud.githubusercontent.com/assets/747161/12010207/08430f32-ac9e-11e5-9eae-dd18c7e97261.png)

**Comment by Samsemilio** [comment]
I have Saskia -> preferences, but there it will only allow me to change my UID or configure communities.

**Comment by Insoleet** [comment]
It's a bug !

**Comment by Insoleet** [comment]
@Samsemilio okay maybe it should appear somewhere else, but I'm no mac expert.

Following the documentation, the `QMenuBar` behaviour is different on macos : 

http://doc.qt.io/qt-5/qmenubar.html#qmenubar-on-os-x

It looks like the `Preferences` will be placed in the system wide menu bar, in the "application menu" (if I understand well, but once again I canno't check) : 
>
config, options, setup, settings or preferences	
Application Menu | Preferences	
If this entry is not found the Settings item will be disabled

Can you manage to find it ?

**Comment by Samsemilio** [comment]
How is it supposed to look on linux? Can you send reference screenshots?

**Comment by Insoleet** [comment]
![prefs1](https://cloud.githubusercontent.com/assets/1170293/12378322/594ada84-bd3a-11e5-9ff9-7d62dc6c22a9.png)
![screenshot_20160117_164948](https://cloud.githubusercontent.com/assets/1170293/12378325/67bc819e-bd3a-11e5-82cf-e26996e4ab4a.png)
