### ISSUE TITLE
Clearly identify the basic income received

### ISSUE THREAD

**Issue by scith** [duniter/sakia#325]
Hello,
In the transactions tab, I see everyday the basic income deposit. I think it "polutes" in a way my transaction feed, as it makes it difficult to keep an eye on the real exchanges. Also nothing says that these are the basic income deposits (I just see that they come from myself). Here is the problem:
![](https://framapic.org/excNwHNKx3ON/ltktmQOqLRhC)
**My whole feed is just basic income deposits...**

**Would it be possible to separate the basic income deposits and the rest?** Here are some ideas:
- Clearly state that this is a basic income deposit rather than a transaction from myself which is unclear (as a comment, with a specific color, etc...)
- A checkbox to hide/show the basic income deposits
- All basic income deposits grouped in an expandable line (click the line in the transaction table to show all basic income deposits)
- Completely remove them from the transaction feed and show them in a different way instead (for instance a "basic income" tab, area or tile)

Thanks

**Comment by Insoleet** [comment]
I agree that something needs to be done. I would plan to go to the following ideas : 
 - A checkbox to hide/show DU
 - Display an icon in the first column :  green when we receive money, yellow when we send money, blue when when we create money

Contributions are greatly appreciated !

**Comment by vtexier** [comment]
Keep in mind that those lines are numerous because there is an UD every day.
I don't think that hiding them is a good idea. We will need them for accountability. 
We just have to show explicitly that it is a UD source.
If we use colors,don't forget color blind  people. Add a tooltip.
