### ISSUE TITLE
Refresh or not refresh ?!

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#333]
When connecting to Sakia I don't know if the informations I have are "up-to-date" or not. I suppose the red light means "not up-to-date", but I cannot see if I can force a "refresh" manually, or wait Sakia to refresh by itself !?

Probably the user lacks information concerning this point.

**Comment by Insoleet** [comment]
Red lights are just a state of the connection to the network. (If we are connected to many synchronized node, the connection is considered healthy, basically.)

Sakia refreshes automatically all the informations when a new block comes in.

**Comment by M5oul** [comment]
A new widget have been added in the bottom-left corner which now display quality of the network.
The red/green led were not very well working.
Feel free to reopen it.
