### ISSUE TITLE
Search Tab : Own identity

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#347]
By default when we open Sakia 0.11.14, in the search tab, it seems that we have : 
- Members who signed own identity
- Members own identity has signed
- Some not-member pubkey (I can see in blue a "cgeek" not member, and another "cgeek" member)

We lack own identity with a special color to identify it. It seems usefull to have own identity in order to control own information and ability to copy/paste own pubkey.

And also it lacks a field with the distance in this tab (said in another issue).

**Comment by Insoleet** [comment]
Yes, some enhancement will come with version 0.12 (notably icons to show informations about transfers / identities / nodes status...)

**Comment by M5oul** [comment]
Is this issue still relevant?
