### ISSUE TITLE
Showing the right balance in my account after a transaction

### ISSUE THREAD

**Issue by samuelandert** [duniter/sakia#351]
My account is not showing the right balance once I make a transaction. I guess the balance value is fetched from the blockchain and only will be updated when the next block is written? 
Maybe you show two different balances. One big one, which is the supposed balance  (maybe even with realtime updating of growing uds) and one smaller one which is representing the actual state, which was last written into the blockchain.

**Comment by Insoleet** [comment]
Fixed in 0.31.
