### ISSUE TITLE
Identity revocation

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#360]
Revocation feature is going to have a major change in UCPv0.2.

Previously, this was just an informative document for nodes to avoid including it in the blockchain. But now I plan to use revocation as a genuine document with a record in the blockchain.

The impact would be to kill the identity: immediate (or almost immediate) ejection from the WoT, no possibility to renew anymore, no possibility to cancel, etc.

This feature is here to destroy definitively the identity, in order to create another one or to counter identity theft.

The revocation document can be created with the identity and won't expire, so we can print it on a paper and use it later on.

So it would be good if Sakia could adapt screens & behavior to warn the user about the existence of the feature + warn him about its power, and avoid easy click on revocation submission.

I will update this issue to link it with protocol changes in ucoin-python-api.

**Comment by M5oul** [comment]
It's implemented and it's working very well.

**Comment by M5oul** [comment]
Related to:
- https://github.com/duniter/sakia/issues/385
- https://github.com/duniter/sakia/issues/386
- https://github.com/duniter/sakia/issues/426
