### ISSUE TITLE
Certifications now have a delay before being written

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#382]
Original change in https://github.com/ucoin-io/ucoin/issues/67

------

A certification made by member A cannot be written if the last certification from A to any member is aged of less than `sigPeriod`.

Protocol rule: https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#certification-chaining

#### Phase 1
Member A certifies member B, now. The cert is written few minutes later.

#### Phase 2
Member A, 10 minutes later, certifies member C. This cert cannot be written now, because `sigPeriod = 3 days` and cert A to B was just written. But in 3 days, the cert will be able to be written.

### Possible behavior for Sakia
So Sakia might refuse to create a certification that won't be written immediately because we've already made a certification few minutes ago.

Or Sakia could add a checkbox in the certification form to make the user confirm "I understand this certification will be written later".

**Comment by Insoleet** [comment]
Also implemented in commit https://github.com/ucoin-io/sakia/commit/916475b21a7b0ed7f6eb1ba80760ef639eb1db1f

**Comment by Insoleet** [comment]
I chose consistency. In sakia 0.12, when the user is not a member, he cannot send any new certification. When the user does not have any certification available, or the certification won't be written yet, it's the same.

**Comment by c-geek** [comment]
Note how in the end, Sakia might not care at all about this rule which is handled on server side.

**Comment by Insoleet** [comment]
Well, it's better if the client is showing a behaviour coherent with what is on the server side :)

**Comment by c-geek** [comment]
I mean: the server would actually accept the certification! But would not write it before `sigPeriod` delay has elapsed since last certification write date. So it is not exactly "the same" as "no certification is available in stock".

So you could allow the user to actually make it, warning him that the made cert has no chance to be written before some time: it would allow him to do *right now* a certification that would be written later.

And that would be just fine if the user had some way to understand why the certification is not written.

Anyway, you implement it the way you want :-)

**Comment by Insoleet** [comment]
I guess I could add such a checkbox. 

For a later version, It'd be great if sakia would show the date of writing authorization on the transaction in the wot tab.

**Comment by Insoleet** [comment]
I changed the behaviour in 0.20.0dev7.
