### ISSUE TITLE
Certifications stock

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#383]
Original change in https://github.com/ucoin-io/ucoin/issues/134

-----

A member cannot issue new certifications as long as he has `sigStock` active certifications already.

Protocol rule: https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#certification-chaining

### Possible behavior for Sakia
Sakia might say how much time is left before a new certification can be written, which will be the time when one of the active certifcations made by the member will expire.

**Comment by Insoleet** [comment]
Same behaviour as https://github.com/ucoin-io/sakia/issues/382
