### ISSUE TITLE
Certifications also have a writability expiry date

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#384]
Original change in https://github.com/ucoin-io/ucoin/issues/128

-----

Protocol rule: https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#certification-writability

A certification written now has a `sigWindow * avgGenTime` delay to be written, otherwise it is considered too old and will be rejected.

This rule is mainly here to avoid spam.

### Possible Sakia bevavior

Certifications sent by uCoin nodes with a too old age should either:

* no more be displayed by Sakia
* be displayed but with a color saying "certification failed to be written and will never succeed"

**Comment by Insoleet** [comment]
Will these certifications be return by URLS **certifiers-of** **certified-by** **lookup** ?

**Comment by c-geek** [comment]
Yes it will, until the server chooses to delete it.
