### ISSUE TITLE
Graphical issue on build?

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#387]
I'm running the build version of Sakia 0.12, I get this horrible graphical interface:

![capture d ecran de 2016-02-27 23-31-49](https://cloud.githubusercontent.com/assets/4758871/13375825/91000afe-ddaa-11e5-8fa6-04a4e7794dc5.png)

When running it, I get this errors under GNOME 3.18, may be it's linked:
```bash
$ ./sakia

(sakia:5988): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « pixmap »

(sakia:5988): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « pixmap »

(sakia:5988): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « pixmap »

(sakia:5988): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « pixmap »
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
```

What do you think?

**Comment by Insoleet** [comment]
There is probably a library missing on travis. Could you try to build it by yourself and tell me how it goes ?

**Comment by M5oul** [comment]
I built it. I have a beautiful graphical interface.

**Comment by Insoleet** [comment]
Ok. I'll have to try what packages are missing then...

**Comment by Insoleet** [comment]
Could you try this build please ? 
https://github.com/ucoin-io/sakia/releases/edit/0.12.1dev2

**Comment by M5oul** [comment]
Same ugly interface.

**Comment by Insoleet** [comment]
Any logs ?

**Comment by M5oul** [comment]
Log looks the same. I have removed the build. I can't download it again to get exact logs output.

**Comment by M5oul** [comment]
With dev3 i get:
```bash
./sakia 

(sakia:5439): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « pixmap »

(sakia:5439): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « adwaita »

(…)

Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
```

**Comment by M5oul** [comment]
Same interface and logs with dev4.

**Comment by Insoleet** [comment]
Ok I guess you'll have to build a sakia version by yourself then... This build is probably too much ubuntu oriented.

**Comment by M5oul** [comment]
It's fixed dev6.
