### ISSUE TITLE
Strange growth and monetary mass values

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#389]
There is something very strange with this values:
- Monetary mass is 9 [zepto](https://fr.wikipedia.org/wiki/Pr%C3%A9fixes_du_syst%C3%A8me_international_d'unit%C3%A9s) (× 10⁻²¹) UD MB
- Growth c is 1 × 10²¹ UD MB

![capture d ecran de 2016-03-17 21-30-19](https://cloud.githubusercontent.com/assets/4758871/13860282/c54c641a-ec87-11e5-9bef-4fea9212ed05.png)

**Comment by M5oul** [comment]
I think monetary mass did a round: it reach his maximum value then goes to his minimal value.

**Comment by Insoleet** [comment]
This is a classic behaviour of computing when reaching maximum value : 0xFFFFFFFF +1 =... 0x00000000 ;)

**Comment by M5oul** [comment]
I close it because it was a bug in duniter database which very high numbers which should not happen in your libre currency life. May be future generations will have to deal with it :smiling_imp:
