### ISSUE TITLE
Transaction duplicated in tx view

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#403]
It's true I am happy to get my Sakia back, but that's a bit too much :smile: 

The duplicated TX was written on [block 29930](http://testnet.duniter.inso.ovh/blockchain/block/29930). Along with the one named "Pingback", which is red.

![image](https://cloud.githubusercontent.com/assets/969136/14440086/a1ed5bc2-002e-11e6-85cc-0b3b43636392.png)

We have blocks every minute, so refresh should have done its job I guess?

**Comment by Insoleet** [comment]
Ahah nice bug. I'll check it out, thanks for reporting !

**Comment by Insoleet** [comment]
Can you share your cache ? Especially the wallet history (should be in `~/.config/sakia/cgeek/__cache__/[pubkey]_wal`

**Comment by c-geek** [comment]
http://up.twiced.fr/f.php?h=1R0X1zn2

**Comment by Insoleet** [comment]
In your cache there are only 3 transfers and I can't find the **SAKIA RULZ** one. Did Sakia crash when you closed it ?

**Comment by c-geek** [comment]
Maybe because of #404.

Deleting the cache cleaned my problem.

**Comment by Insoleet** [comment]
You mean, you were restarting sakia and the multiples transactions were always present ?

I found a bug with the way I was handling websockets blocks coming in, it was causing many rollbacks with our network speed. I fixed it in next release. Coupled with another bug I found in rollbacks, maybe it was causing problems.

**Comment by c-geek** [comment]
Yes I restart multiple times and always had these duplicates. Only manual cleaning of the __cache__ folder helped.

**Comment by Insoleet** [comment]
I think it never happened since then. I think less forks and rollback fix fixed it.
