### ISSUE TITLE
No more the right to issue certifications

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#407]
OK there is a misunderstanding here, I face this screen:

![image](https://cloud.githubusercontent.com/assets/969136/14502192/60beed5a-01aa-11e6-8235-dbbdc995262c.png)

How could I be stuck? I should always be able to send any certification, it is just that the node won't be able to write it right now. Because there is no need to make the user wait to send its certification. Could we use such a behavior instead?

Also, I don't have the units for `9:18`. I guess it is hour:minutes, but not sure.

Could you tell me how Sakia decides the remaining time? Because it seems this parameter in super_currency is `0`, so there is something strange:

![image](https://cloud.githubusercontent.com/assets/969136/14502415/722e74d8-01ab-11e6-80fc-9a01edafdf62.png)

**Comment by Insoleet** [comment]
The code is using the `sigPeriod` parameter. So the code is correct. Here is exactly the calculation made : 

```python

    async def cert_issuance_delay(self, identities_registry, community):
        """
        Get the remaining time before being able to issue new certification.
        :param sakia.core.Community community: the community
        :return: the remaining time
        :rtype: int
        """
        certified = await self.certified_by(identities_registry, community)
        if len(certified) > 0:
            latest_time = max([c['cert_time'] for c in certified if c['cert_time']])
            parameters = await community.parameters()
            if parameters and latest_time:
                current_time = await community.time()
                if current_time - latest_time < parameters['sigPeriod']:
                    return parameters['sigPeriod'] - (current_time - latest_time)
        return 0
```

It looks like the `current_time - latest_time` returned something negative. Can you check the community parameters in the informations tab just to be sure?

What is possible is that the forks of the network are happening so often that they are breaking some asynchronous code... It looks like the network forked between the computation of latest certification time and the computation of current network time, which led to a wrong computing of remaining time.

**Comment by c-geek** [comment]
Very good :+1: 

![image](https://cloud.githubusercontent.com/assets/969136/15193548/b6ca7dc0-17be-11e6-819d-8da60019e172.png)
