### ISSUE TITLE
New peering document does not override previous document

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#411]
Here is the symptom. I have the following screen right now:

![image](https://cloud.githubusercontent.com/assets/969136/14941711/c96499fa-0fa5-11e6-906a-ac6f5885bc89.png)

And if I trigger a peering renewal on another node that isn't listed here, I get the following:

![image](https://cloud.githubusercontent.com/assets/969136/14941715/ef76a2dc-0fa5-11e6-998f-255989f05965.png)

As yo ucan see, node `2QyFF` has appeared (so some node sent a peering document using websockets) but is marked offline.

So I try to go to my node to check the new peering value, and I see:

```json

{
  "version": 2,
  "currency": "test_net",
  "endpoints": [
    "BASIC_MERKLED_API cgeek.fr 88.174.120.187 9332"
  ],
  "block": "1920-00003204179A3EFC5911B2A9F892EDA40F8F90F080D36B1192FDA8F09CEAA1D0",
  "signature": "x4BkEx3IjWBPwUVpHacMpoXKNHNM2b6OPAF3wRDOj4JkGW8sCp44att0VSEiV94o79C5kLuk69H4jdVbQ3VtCA==",
  "raw": "Version: 2\nType: Peer\nCurrency: test_net\nPublicKey: 2QyFFBkv2JdUAXdPzVN3jP7QzBrw6rB2oeB9tyzTTaPg\nBlock: 1920-00003204179A3EFC5911B2A9F892EDA40F8F90F080D36B1192FDA8F09CEAA1D0\nEndpoints:\nBASIC_MERKLED_API cgeek.fr 88.174.120.187 9332\n",
  "pubkey": "2QyFFBkv2JdUAXdPzVN3jP7QzBrw6rB2oeB9tyzTTaPg"
}
```

So the new port `9332` is not used by Sakia, which seems to use the old definition instead (port `37355`).

Just to be sure I tried Simple WebSocket Client to check if what was spread arount the network was the actual new peering document, and I got:

```json
{"version":2,"currency":"test_net","pubkey":"2QyFFBkv2JdUAXdPzVN3jP7QzBrw6rB2oeB9tyzTTaPg","block":"1921-00003456B2E729CFA32A0E550E594B620EE8C0ADEDD88A4A4F7D58E11F56E5D1","signature":"SveN5lKn+4zZaDG/dA7wZvdLGPSHbjZABR1/XTAQb1SsdnAkTbcGL0Fva5NhxrbVvaJR2r++cUx3lEvO7l4kDg==","endpoints":["BASIC_MERKLED_API cgeek.fr 88.174.120.187 9332"],"raw":"Version: 2\nType: Peer\nCurrency: test_net\nPublicKey: 2QyFFBkv2JdUAXdPzVN3jP7QzBrw6rB2oeB9tyzTTaPg\nBlock: 1904-000027753E0A5C8310534F34B7DA491D870B7CB61A655D119EF675A24FE6D700\nEndpoints:\nBASIC_MERKLED_API 88.174.120.187 2a01:e35:8ae7:8bb0:9caa:4800:96aa:941f 37355\n"}
```

which indeed is the new.

So I conclude Sakia does receive the new peering document, but for some reason use the old document for network layer instead.

**Comment by c-geek** [comment]
Also, removing the cache displays this:

![image](https://cloud.githubusercontent.com/assets/969136/14941739/27ab07d2-0fa7-11e6-9b70-4965d5d3ffc3.png)

And triggering the peering renewal gives this:

![image](https://cloud.githubusercontent.com/assets/969136/14941743/37e3f3f2-0fa7-11e6-8349-31fa9e28ab9e.png)

**Comment by c-geek** [comment]
OK got it: the `raw` field is wrong. :-)

**Comment by c-geek** [comment]
However I don't close because if Sakia did check the signature, it would have detected the problem and not interpreted the fake raw field (it seems to be modified by a propagating node).

**Comment by Insoleet** [comment]
Nice catch and analysis. Indeed, Sakia does not check any signature at the moment. I'll fix it at least for the network crawling... But it should be done for any document in the end.

**Comment by Insoleet** [comment]
I think I fixed it but I'm not sure how to test. How do you trigger peer broadcasting ?

**Comment by c-geek** [comment]
Go to DuniterUI > Settings > Network > Save and apply settings.

This will immediately trigger a new Peer document broadcast. You can do this up to approx. 30 times before you have to wait one new block to make one other try. So be cautious :smile:
