### ISSUE TITLE
WoT graph: bidirectionnal links are not displayed

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#413]
As mentionned [in this message](https://forum.duniter.org/t/ask-for-certification-thatoo/820/4?u=cgeek), I have a both-way link with Moul which displays as one-way link.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/969136/14957161/0446a296-1084-11e6-8f88-ae2dfbbc1cb5.png)

**Comment by M5oul** [comment]
From my point of view, I see an arrow from cgeek identity toward mine.

**Comment by Insoleet** [comment]
Fixed in https://github.com/duniter/sakia/commit/a6b0eba5b5ce40d17e1e3d2a71febc91ca8758ea
