### ISSUE TITLE
Network discovering issue

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#417]
I delete my local account which remove known network.
I add my account from my node (moul.re), it discover one of cgeek node.
![capture du 2016-05-04 14-34-01](https://cloud.githubusercontent.com/assets/4758871/15014290/773cd162-1205-11e6-83e9-f49b2310438b.png)
Then I wait ten minutes, click on the refresh button and other nodes do not appear.

**Comment by Insoleet** [comment]
Yes, nodes are now discovered through the websockets, when peer documents are propagated by the network. If a node does not answer to websockets, it uses HTTP as fallback. I think it's the correct behaviour, what do you think @c-geek  ?

**Comment by c-geek** [comment]
Yes it is correct.

Maybe, however, it would be a good thing if Sakia made a network discovering on startup. Just to see the whole network, and then rely on new peer documents to update the view.

What do you think of this @Insoleet?

**Comment by Insoleet** [comment]
This is totally possible but I wonder how this will go when the networks starts to have thousands of nodes... But I could probably discover some nodes on startup, but not every nodes.

**Comment by Insoleet** [comment]
Manual refresh will initiate full HTTP GET peers refresh.
