### ISSUE TITLE
Configure → Delete account deletes the wrong one

### ISSUE THREAD

**Issue by Karmak23** [duniter/sakia#425]
To reproduce the Bug :

- create 2 accounts (say "Karmak23" and "OlivierCortes")
- open account "Karmak23"
- click Account → Configure
- type "OlivierCortes" in the field, then hit "remove account" (to remove OlivierCortes and keep Karmak23
- BOOM (Current account Karmak23 is deleted, and OlivierCortes is kept).

**Comment by Insoleet** [comment]
Ah, this is more a UX failure than a bug. The delete button is supposed to remove the current account, and the edit input is here to rename the account.

This has to change.
