### ISSUE TITLE
Time precision on transaction tab

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#427]
While trying to send my second transaction, (I saw no problem for the first, bu I cannot be sure). I succeeded to make a screen capture of the error message notification : 

![sakia020dev9](https://cloud.githubusercontent.com/assets/5245398/15245388/708d11d0-1906-11e6-914e-37ffaf6acf70.png)

End the transaction is good in the transaction tab, so while seeing error message I made a "send" again, same error message, but then the same transaction was made two times...

![sakia020dev9_2](https://cloud.githubusercontent.com/assets/5245398/15245414/9c771818-1906-11e6-9e1b-aa488c93c4ab.png)
- missing hour in the transaction tab, could be helpfull to have it...

**Comment by c-geek** [comment]
If an hour transaction tab is added, a second one with "written time" could also be helpful.

**Comment by blavenie** [comment]
why not have the elapsed time also ?  (like "2 second ago", "An hour ago"...)
This is commonly used on FaceBook, Diaspora, ... and Cesium ;)

**Comment by M5oul** [comment]
> missing hour in the transaction tab, could be helpfull to have it…

Time could be displayed when passing the cursor on the date column.

> \<vit\> Moul: attention aux besoins spontanés. Vous avez besoin de l'heure affichée car vous déboguez des transactions. Sur un relevé de banque, on ne l'a jamais et ça ne gêne personne. Ici on l'a, en bulle d'aide, mais si on l'affiche tout le temps , le listing devient trop chargé et illisible... amha

We could consider those information as debug and display sent and written times of the transaction in two additional columns only if Sakia is set in expert mode.

Personally, I consider that it's interesting to display at least sent or written time by default to have more precise time about transaction.
We could only display hour and not minutes. I prefer minutes displayed.
No need to display second and time zone type.

> Sur un relevé de banque, on ne l'a jamais et ça ne gêne personne.

It hind me.
Bank transaction are not very fast, so may be this precision on time could be more or less 24h.
With Duniter, we could have almost instant transaction around 5 minutes.

> le listing devient trop chargé et illisible

It's a valid argument, but I don't think transaction tab is very full of information.
We could also [merge transaction amount in one column](https://github.com/duniter/sakia/issues/429) to reduce horizontal space.

**Comment by M5oul** [comment]
I split this issue in two: https://github.com/duniter/sakia/issues/430

**Comment by M5oul** [comment]
For instance in Cesium:

![blob](https://cloud.githubusercontent.com/assets/4758871/15268753/a926f284-19e9-11e6-9a28-96d90b4e5b09.png)

**Comment by Insoleet** [comment]
You have the detailed time if you pass your mouse over it.

I don't think it's necessary to add that much details in this column.
