### ISSUE TITLE
Transaction issue

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#430]
While trying to send my second transaction, (I saw no problem for the first, bu I cannot be sure). I succeeded to make a screen capture of the error message notification : 

![sakia020dev9](https://cloud.githubusercontent.com/assets/5245398/15245388/708d11d0-1906-11e6-914e-37ffaf6acf70.png)

End the transaction is good in the transaction tab, so while seeing error message I made a "send" again, same error message, but then the same transaction was made two times...

![sakia020dev9_2](https://cloud.githubusercontent.com/assets/5245398/15245414/9c771818-1906-11e6-9e1b-aa488c93c4ab.png)

+ missing hour in the transaction tab, could be helpfull to have it...

**Comment by Insoleet** [comment]
You never received any source before sending your transaction, that's why you didn't have any source  to consume.

The blue is not an error, it's an unsent transaction that needs to be sent when you receive new sources.
