### ISSUE TITLE
Add a way to retrieve the salt

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#431]
Simple users like @galuel have difficulties to remember their cryptosalt as they see it only once in the usage of Sakia, at registration phase.

Sakia is obviously memorizing it, since it only asks for the password to process operations like sending money. It would be great to be able to retrieve it in some way using the UI.

For example, it could be displayed if we successfully give the associated password.

**Comment by Insoleet** [comment]
Invalid since 0.31.
