### ISSUE TITLE
Salt = "secret key" = "clé secrète" + password

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#432]
Le "salt" n'est pas le"ID" mais pourtant lui-seul permet de se connecter associé au password. Donc le ID est inefficient techniquement autant que pratiquement, ce n'est qu'une information générale, tout comme le champ commentaire des transactions.

Mais il doit rester secret, il est alors aussi secret que le password, c'est une seconde couche de password, un "password secret" (alors que le password est déjà censé être secret !).

Donc pourquoi ne pas gérer un seul password, ou bien différencier deux niveaux de password ? Conceptuellement pour l'utilisateur ce serait plus clair, alors que tel que présentés, les concepts s'embrouillent et sont difficiles à comprendre pour une première utilisation.

Dans ce cas, il faut l'appeler du genre "phrase secrète" ou "clé secrète" un truc plus clair.

La connexion se fait alors par : "clé secrète" + password, puisque le tout suffit à se connecter. L'UID n'est qu'une information conceptuelle, sans intérêt technique (pas plus que le champ commentaire des transactions in-fine). L'UID peut-être utilisé à d'autres fins (notamment de consultation), mais c'est autre chose. Il vaut donc mieux orienter les utilisateurs vers les données nécessaires et pas les données secondaires (UID) en terme d'usage.

**Comment by Insoleet** [comment]
Ok, here is what I'll do : 
- I will remove UID field from "new account dialog"
- When publishing an identity to a community, the user will be able to choose an UID
- Only the secret key + password will be needed when creating a new account/connecting
