### ISSUE TITLE
salt - entropy don't match the good user concept.

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#434]
Je peux parler d'"entropie" pour spécifier la manière dont l'algorithme fonctionne, c'est général, mais ça ne spécifie pas l'entropie personnelle choisie par l'utilisateur au final. Tout comme "variable" ne dit pas la valeur spécifique 10 ou 25 que l'on met dedans.

I propose so to use : "secret key" = "clé secrète", and inform the end user that he has two password levels to connect to its account, he can keep in separated points : 

- secret key
- password

And use those concepts in all clients will help to understand what it is about : some secret own passwords able to connect to its account to manage it.

**Comment by Insoleet** [comment]
It has been done in 0.20.
