### ISSUE TITLE
Sakia 0.20dev10 à planté

### ISSUE THREAD

**Issue by Chrisaiki** [duniter/sakia#437]
Ce matin, vers 11.00 jeudi 19 mai  Sakia 0.20dev10  sur win10 64 bits à planté, sans raison apparente ?? La fenêtre se ferme toute seule
Lorsqu'on relance, Sakia s'ouvre et se ferme en moins d'1s.

**Comment by M5oul** [comment]
As-tu des logs ?

**Comment by Insoleet** [comment]
Le lancer avec l'argument -d pour obtenir des logs. Un fichier de logs sera généré dans %APPDATA%/sakia/sakia.log. merci !

**Comment by Chrisaiki** [comment]
Ben voilà
[sakia_txt.txt](https://github.com/duniter/sakia/files/274666/sakia_txt.txt)
C'est marrant github accepte pas les .log

**Comment by M5oul** [comment]
```fish
Exception handler executing
Task exception was never retrieved
future: <Task finished coro=<refresh() done, defined at sakia\gui\community_tile.py:78> exception=AttributeError("'NoneType' object has no attribute 'number'",)>
Traceback (most recent call last):
  File "asyncio\tasks.py", line 239, in _step
  File "sakia\gui\community_tile.py", line 102, in refresh
  File "sakia\core\registry\identity.py", line 511, in requirements
  File "site-packages\duniterpy\documents\block.py", line 50, in __eq__
AttributeError: 'NoneType' object has no attribute 'number'
```
