### ISSUE TITLE
When a node sync, network blinks a bit

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#439]
See the first node of the list, `win-dev.cgeek.fr`, it has just been put on after a week-end off and is currently pulling a lot of blocks from the network and send each block added to its blockchain on the /block websocket.

This makes Sakia Network tab blinking a bit, but for sure this would be worse if 2 nodes were to do the same (syncing) at the same moment.

![image](https://cloud.githubusercontent.com/assets/969136/15643008/2b57b69a-264b-11e6-809e-21ea38a17a86.png)

**Comment by Insoleet** [comment]
Yes currently, this is done really badly because every nodes are refreshed when we receive a new block. This has to be enhanced.
