### ISSUE TITLE
First created identity are displayed non validated in WoT view

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#442]
First created identity are displayed non validated in WoT view:
![capture du 2016-06-03 11-56-13](https://cloud.githubusercontent.com/assets/4758871/15775532/a3d64520-2982-11e6-8ed4-e86d2e9ae139.png)

**Comment by Insoleet** [comment]
I didn't understand the problem. Can you add more informations please ?

**Comment by M5oul** [comment]
Validation `0/6` is displayed between `cgeek` and `moul` identities.

**Comment by Insoleet** [comment]
Well probably that the certification was not validated and is only in the pool ! Did you find it validated in some url ?

**Comment by M5oul** [comment]
This fix reduced number of `0/6` displayed.
There is still some certifications at `0/6`. May be this validations certifications are legit because of there are may be not written in blockchain.

I close it as it seems good.
