### ISSUE TITLE
problème d'install sous windows 32 et 64 sous Windows 7 pro

### ISSUE THREAD

**Issue by Artichit** [duniter/sakia#448]
Voila le message que j'obtiens à l'install: 
![capture d ecran 2016-06-05 11 18 01](https://cloud.githubusercontent.com/assets/19758773/15804621/9eb06326-2b0f-11e6-9b64-29aa2f1265bc.png)

**Comment by Insoleet** [comment]
Oui, oublie de ma part lors des RML7 : il faut installer ça sous Windows : https://www.microsoft.com/fr-fr/download/details.aspx?id=48145

**Comment by Artichit** [comment]
Merci beaucoup!!! Ca devrait marcher du coup...
Bises!
Ariane.

2016-06-06 12:33 GMT+02:00 Insoleet <notifications@github.com>:

> Oui, oublie de ma part lors des RML7 : il faut installer ça sous Windows :
> https://www.microsoft.com/fr-fr/download/details.aspx?id=48145
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/duniter/sakia/issues/448#issuecomment-223923420>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AS1-tZwJzsMF3xDoDKQVpEsfK16WcTuPks5qI_ePgaJpZM4IuUQA>
> .
>



-- 
Ariane TICHIT
CERDI
63-65 Bd F. Mitterrand
63000 Clermont-Ferrand
0473177414

**Comment by blavenie** [comment]
Ca c'est une marraine motivée ! Déjà sur le sujet ? ;)
Bises à toi, et encore merci pour ta présence

**Comment by Artichit** [comment]
Coucou Benoît!

Oui je vais m'y mettre sérieusement!! Plein de trucs à boucler aussi pour
ma fin d'année universitaire donc je ne vais pas pouvoir avancer au rythme
auquel je voudrais là-dessus, mais je suis convaincue que vous tenez un
moyen de libération de l'homme du carcan monétaire hyper puissant et que la
blockchain, par ailleurs, va permettre des innovations étonnantes et
libératrices également dans d'autres domaines. Donc oh que oui je suis
motivée!!!
a très bientôt and keep going!
Ariane.

2016-06-06 21:00 GMT+02:00 Benoit Lavenier <notifications@github.com>:

> Ca c'est une marraine motivée ! Déjà sur le sujet ? ;)
> Bises à toi, et encore merci pour ta présence
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/duniter/sakia/issues/448#issuecomment-224054967>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AS1-tVddXtmx9D6iZsaM6NayvNvyMxRGks5qJG5qgaJpZM4IuUQA>
> .
>



-- 
Ariane TICHIT
CERDI
63-65 Bd F. Mitterrand
63000 Clermont-Ferrand
0473177414
