### ISSUE TITLE
Who is a sentry ?

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#449]
In test-net sakia 0.20.0dev10 we have in WoT information : 

0,9 = minimum percent of "sentries" to reach to match the distance rule

90% would be better, and % is a good symbol to use instead of the word "percent".

Who is a "sentry" ? It is not clear : Am I a "sentry" ? How can I see it and control it is right ? Who are the other "sentries" ? Is there a "sentry" sub-WoT to check for controls ?

Can we have a link towards a sakia wiki - webpage inside sakia, to click and to understand where this rule can be explained, and how to check this in sakia and control it as a money member ?

**Comment by Insoleet** [comment]
Yes with  @c-geek we talked about it and indeed it is important to show who is a sentry and who is not.

**Comment by Insoleet** [comment]
Fixed in latest release. Sentries have bold borders.
