### ISSUE TITLE
WoT Panel double rendering

### ISSUE THREAD

**Issue by charlyoleg** [duniter/sakia#451]
With the 'test_net' currency, in the WoT, if you select 'myckeul', you will see 'charlyoleg' bubble twice. The same effect appears with 'cgeek'. Both have certificated me ('charlyoleg'). I have done two unconventional actions that might be the root cause of the double creation of the bubble with 'charlyoleg':
- In the main panel, add a community, I have done twice this action once with "register your account", once with "connect using your account". That was performed before 'myckeul' and 'cgeek' registered me.
- In the 'test_net' panel, I may have clicked twice on the "renew ownership" button.

**Comment by charlyoleg** [comment]
![sakia_double_charlyoleg_bubble](https://cloud.githubusercontent.com/assets/2923494/15909839/6e845c5a-2dc8-11e6-9eea-6b93d5e59a6c.png)
On the snapshot you can even see 3 "charlyoleg" bubbles now because I have certified "myckel". I understand the left and the right "charlyoleg" bubbles. But I don't expect the one on the top.

**Comment by Insoleet** [comment]
Ah this is totally normal. This is a view of the certifications received and sent on the WoT. That's why you see you 3 times : 
- On the left, these are the certifications received by myckeul
- On the right, sent by myckeul
- On the top, the path between you and myckeul in the WoT

**Comment by charlyoleg** [comment]
Thanks. The issue is closed.
