### ISSUE TITLE
Package vs2015 with the releases

### ISSUE THREAD

**Issue by Insoleet** [duniter/sakia#456]
Maybe @c-geek has an idea using the installer ? :)

**Comment by c-geek** [comment]
I do not know precisely, but you could follow [this forum post](https://forum.duniter.org/t/probleme-dinstallation/863/6?u=cgeek).

**Comment by Insoleet** [comment]
I remembered you talked about it but I forgot where. Thanks !

**Comment by Insoleet** [comment]
This should be done in https://github.com/duniter/sakia/commit/6cb63079b4473a52747844fe17389a3209e27447

**Comment by c-geek** [comment]
Awesome :+1:
