### ISSUE TITLE
Launcher doesn't work in Ubuntu 14.04

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#459]
Installing Sakia 20.1 works fine with the .deb. Launching Sakia directly with the terminal works fine, but the launcher appears in Unity menu, but doesn't work (no reaction).

So I made a specific launcher on my desktop (this is not trivial to do, check the file), that works fine, I attach it for information. Sakia.desktop is the name of the launcher, I join it as .txt to upload it.
[Sakia.desktop.txt](https://github.com/duniter/sakia/files/306328/Sakia.desktop.txt)

**Comment by Insoleet** [comment]
Is it fixed with latest releases ?

**Comment by galuel** [comment]
It seems ok to me. I deleted my launcher, launched sakia from terminal, and the icon is ok and kept in Unity.
