### ISSUE TITLE
Noeuds membres sans UID ?

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#465]
Dans sakia je vois des noeuds membres mais, certains, sans leur UID (alors que je vois leur pubkey)... sur "clic droit ouvrir dans le navigateur" ça n'ouvre rien... Donc je ne peux pas contrôler qui c'est...

Mais en sus puisqu'il est membre, pourquoi je ne pourrais pas voir directement via clic droit, où il est dans la WoT, de manière à pouvoir demander aux contacts de mes contacts de qui il s'agit !?

Note : sous Ubuntu 16.04 - 64 bits

**Comment by Insoleet** [comment]
Should be back in 0.31
