### ISSUE TITLE
Network view: block sorting is not using bloc number

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#470]
As we can see in this screen, Galuel's block is 1999 and it is placed in first place for a descending ordrer, which is not correct:

![image](https://cloud.githubusercontent.com/assets/969136/16299908/2d4471b4-393d-11e6-8c2b-b8a2c4711759.png)

**Comment by M5oul** [comment]
Yep, I have noticed that this is a string comparison and not an integer one.
