### ISSUE TITLE
4 times the same transaction

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#471]
In sakia 0.20.2 I can see 4 times the same transaction, I put Cesium to check it in the capture screen.
![sakiacesium](https://cloud.githubusercontent.com/assets/5245398/16380628/7ce3f684-3c78-11e6-8b60-3c8dd368f851.png)

**Comment by M5oul** [comment]
This is UD which are displayed four times.

**Comment by c-geek** [comment]
@M5oul not only UDs, have a closer look: all its sources are displayed 4 times.

Also I confirm I had this bug several times in the past.

**Comment by Insoleet** [comment]
Well the algorithm reading the blockchain is pretty bad and has a lot of bug. It should be fixed some time.
