### ISSUE TITLE
Let the user decide if a salt/password is OK or not

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#472]
When we enter a "low" salt/password, the software prevents the user from continuing and use the salt/password if has entered. This is done for security purposes, that's fine.

But we should give the user an option to force this usage, despite the security alerts. Because we want users to be free to make the decisions he wants.

Also, we should be able to use accounts created on another sofware which might have other security rules, uncompliant with the software own rules.

**Comment by Insoleet** [comment]
Well I don't want to let users choose bad passwords with sakia. But for sure they should be able to connect using an account from another software : the password filter should be present when connecting.

**Comment by c-geek** [comment]
> Well I don't want to let users choose bad passwords with sakia.

This is not very compliant with relativity principle..

**Comment by Insoleet** [comment]
Well the network is neutral but the clients can enforce some behaviours... for the safety of the network. Users are still free to use other clients/publish their own identity documents thought. 
Let's not forget that if users uses too weak keys, they can be stolen and used to get more node power in the network ! So I prefer that we have strong rules when the clients are used to create new accounts.

But, I agree, users should be able to connect to sakia using any salt/password. I only want to enforce it when creating a new identity.

**Comment by c-geek** [comment]
> Maybe this protection could be disabled in expert mode ?

Yes, good idea!
