### ISSUE TITLE
Transactions do not add up to Balance

### ISSUE THREAD

**Issue by RavanH** [duniter/sakia#477]
Looking at my Transactions tab un Units, see screen print 
![sakia tn](https://cloud.githubusercontent.com/assets/1184853/16519971/154ae43e-3f8d-11e6-9309-5db51906c3b3.png)
(Sakia 0.20.2)

It sais my Balance is 6 727 360 TN (there is a comma missing there I think) which corresponds with the info on Cesium wallet page. But when I add up all transactions, I arrive at 5 018 755 TN

I suspect the issue is the deposit of **189 845 TN on 30/06/2016** (from Juan) which on Cesium shows as **1 898,450 TN**, which (if we ignore the missing comma in Sakia) is 10 times as much! I suspect Cesium is right, because then the transactions add up to the total balance amount...

![cesium tn](https://cloud.githubusercontent.com/assets/1184853/16520213/f15cab5a-3f8e-11e6-87c6-cb50467818d8.png)

**Comment by Insoleet** [comment]
@blavenie : What are you using to display the value of the wallet ?

**Comment by RavanH** [comment]
In Sakia I set it to "Unités" and Cesium has the option "Use relative unit" switched OFF for easy comparison.

Ref : https://forum.duniter.org/t/difference-between-amounts-in-cesium-and-sakia/1028

**Comment by vtexier** [comment]
fixed in 16b566f
