### ISSUE TITLE
Critical error when trying to send money

### ISSUE THREAD

**Issue by jytou** [duniter/sakia#481]
Version 0.20.3 under Linux.

I'm trying to send money and when typing the amount in the dialog in UD, I got the following error window:
A critical error occured. Select the details to display it. Please report it to the developers github

The detail of the error is the following:
`Task exception was never retrieved
future: <Task finished coro=<relative_amount_changed() done, defined at sakia/gui/transfer.py:185> exception=Exception('Test',)>
    ----
    Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/transfer.py", line 187, in relative_amount_changed
Exception: Test`

Then when I click on the Ok button, it tells me that there is no amount.

If I try to type a random amount in test_net instead of DU, (which should be allowed as well and could have saved me), the Ok button never gets enabled (I have chosen a recipient) so I can't send money that way either.
Here are a few more facts after testing a little more. If I type an amount that ends with one '0', the OK button is activated. But I can still type an amount that is much higher than my account balance so there is no real check if the amount is valid or not, yet it is forced to end with a 0. I guess this check is because of the base 1 switch, but we're losing precision here, and will it be 2 '0's when we switch to base 2 and so on? There ought to be a better solution...

**Comment by Insoleet** [comment]
Ah damn it, big mistake. This was a test code, no idea why it leaked to releases... I'm building a new release right now.
