### ISSUE TITLE
Send money window doesn't show Password dialog and gets stuck

### ISSUE THREAD

**Issue by jytou** [duniter/sakia#482]
Trying to send money with version 0.20.4, the send money dialog sometimes doesn't display the password dialog and gets stuck:
![screenshot from 2016-07-14 13 44 44](https://cloud.githubusercontent.com/assets/6391882/16839090/732e95b0-49cd-11e6-8de7-de3ef14c5c55.png)

I have tried switching on logs and got the following file, but it doesn't seem to contain any meaningful information regarding this problem:
[logs.zip](https://github.com/duniter/sakia/files/363670/logs.zip)

The interesting part is that this is not 100% reproducible: it will work sometimes (the password window appears and everything works), and if I try again even without restarting sakia it will get stuck. It gets stuck more often than it works. Thus I have a feeling this may be multi-threading related at some point in the UI.

I don think this is related, but after a long while I sometimes have the following messages in the command line output:
`QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"`

I am running:
Ubuntu 14.04.4 LTS
Linux ****** 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I simply downloaded the sakia-linux.zip file, unzipped it and ran it. I did not have this problem with previous releases (0.20.2 and lower).

**Comment by Insoleet** [comment]
You should try this again and paste the logs here if it is not working.

**Comment by M5oul** [comment]
I could reproduce the bug.

**Comment by Insoleet** [comment]
Could you run sakia in debug mode, reproduce the bug and copy/paste the logs please ?

**Comment by M5oul** [comment]
It happen when playing on searching identity:
```bash
DEBUG:transfer:accept:Accept transfer action...
DEBUG:transfer:accept:checking recipient mode...
DEBUG:transfer:accept:checking amount...
DEBUG:transfer:accept:Showing password dialog...
DEBUG:password_asker:reject:Cancelled
DEBUG:transfer:accept:Accept transfer action...
DEBUG:transfer:accept:checking recipient mode...
DEBUG:transfer:accept:checking amount...
DEBUG:transfer:accept:Showing password dialog...
DEBUG:password_asker:reject:Cancelled
```

**Comment by Insoleet** [comment]
Ok I think I got this one. Please tell me if you can still reproduce it in next release.
