### ISSUE TITLE
Link not clickable on Critical error window

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#486]
Furthermore, I can't close the window with the cross :smile:
With `Ok`, it close.

**Comment by Insoleet** [comment]
Well it seems to be a bug from QT : 
http://stackoverflow.com/questions/10028608/qmessagebox-with-link-inside-unable-to-click
https://bugreports.qt.io/browse/QTBUG-21960

If anyone got an idea how to fix this, any pull request is welcome...
