### ISSUE TITLE
Critical Error Report

### ISSUE THREAD

**Issue by Idyllei** [duniter/sakia#490]
I received an error and was instructed to report it to the developers on GitHub. Seeing as it came from the Sakia program, I am reporting it here.

I use Sakia v. 0.20.5. I'm on Windows 10 running Avast! Antivirus and MalwareBytes AntiMalware. 
I am at block 25675 currently. I am using Eastern time (-5:00 GMT) and it is about 4:30 PM (14:30) on 27 July 2016.

The error:
```

    Task exception was never retrieved
future: <Task finished coro=<refresh_path() done, defined at sakia\gui\member.py:112> exception=NetworkXError('The node 5bxtdmC7RGGJEmcdnJ3ut5zg7KdUH2pYZepSHbwNYs7z is not in the digraph.',)>

    ----
    Traceback (most recent call last):

  File "site-packages\networkx\classes\digraph.py", line 756, in predecessors_iter

KeyError: '5bxtdmC7RGGJEmcdnJ3ut5zg7KdUH2pYZepSHbwNYs7z'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "asyncio\tasks.py", line 239, in _step

  File "sakia\gui\member.py", line 124, in refresh_path

  File "sakia\core\graph\wot_graph.py", line 58, in get_shortest_path_to_identity

  File "site-packages\networkx\algorithms\shortest_paths\generic.py", line 136, in shortest_path

  File "site-packages\networkx\algorithms\shortest_paths\unweighted.py", line 136, in bidirectional_shortest_path

  File "site-packages\networkx\algorithms\shortest_paths\unweighted.py", line 195, in _bidirectional_pred_succ

  File "site-packages\networkx\classes\digraph.py", line 758, in predecessors_iter

networkx.exception.NetworkXError: The node 5bxtdmC7RGGJEmcdnJ3ut5zg7KdUH2pYZepSHbwNYs7z is not in the digraph.

    
```

**Comment by Insoleet** [comment]
Thanks for the report.

Do you know what were you doing when the error poped up ?

**Comment by Idyllei** [comment]
I had Sakia running in the background (the GUI was opened), and I was browsing the Internet when I heard the Windows error sound. That is when I checked for the problem and saw the error window. (I can narrow down the websites I was browsing to Reddit and GitHub in my browser.)

**Comment by Insoleet** [comment]
What was the GUI opened on ? Were you in a specific tab/window ? What was the content of the tab/window ?

This would be of great help if you can remember.. :+1:

**Comment by Idyllei** [comment]
I was very likely in the `test_net` tab of my client. Either in `Transaction` or `Network`:

![Likely Tab 1](https://s31.postimg.org/kpzqztsg7/Screenshot_2.png)
![Likely Tab 2](https://s31.postimg.org/55sd9aibr/Screenshot_3.png)

**Comment by Insoleet** [comment]
Okay

Did you do anything like looking for any member information or transfer any money before reducing sakia ?

**Comment by Idyllei** [comment]
Yes, I looked at cgeek's information and Jean-F's info. I also viewed cgeek in the WoT.

**Comment by Idyllei** [comment]
I tested the Information tab. Within 5 minutes of opening the Information tab for Jean-F, I received the same error.

**Comment by Insoleet** [comment]
Perfect, you tracked down the bug ;) Thanks, I'll be able to take a look and try to fix this !
