### ISSUE TITLE
Certifications sent: 41/40

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#492]
That's a bit confusing, here is a screenshot: 

![image](https://cloud.githubusercontent.com/assets/969136/17210848/b7ad8892-54c5-11e6-8525-ea1cf564131a.png)

If I have a look at http://cgeek.fr:9330/wot/certified-by/cgeek, I can see the 41 certifications. But not all are written of course, otherwise I would have a serious protocol issue :smile: 

Could it be added some kind of extra informations like `(+2 certifications pending)`, so we would have something like:

    Certifications sent: 39/40 (+2 certifications pending)

And really disable the "Certifiy" button when we have `40/40` certifications written?

**Comment by Insoleet** [comment]
This thing is kind of a bug actually, so I'll fix it for next minor release ;)
