### ISSUE TITLE
No more transaction is displayed

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#515]
I could not see the UDs of the last 2 days (20 & 21 of August 2016), so I closed Sakia and cleared the cache. I restarted Sakia and now I can't see any transaction nor UD, however I did see Sakia transactions loading bar.

![image](https://cloud.githubusercontent.com/assets/969136/17848282/db91228c-6852-11e6-9bc7-9990b7d66177.png)

**Comment by Insoleet** [comment]
I think in the logs you can find Exceptions being printed during the refresh procedure.  It's probably caused by a block being misinterpreted which stops the blockchain parsing right away (https://github.com/duniter/sakia/blob/master/src/sakia/core/txhistory.py#L303)

**Comment by M5oul** [comment]
I could reproduce it.
I may be found interesting logs:
```bash
DEBUG:api:requests_get:Request : http://duniter.youpeek.net:8999/blockchain/block/34616
DEBUG:api:requests_get:Request : http://duniter.help-web-low.fr:8999/blockchain/block/34653
DEBUG:api:requests_get:Request : http://87.91.122.123:9330/blockchain/block/34658
DEBUG:api:requests_get:Request : http://87.91.122.123:9330/blockchain/block/34662
DEBUG:txhistory:_refresh:Could not parse field IssuersFrameVar
DEBUG:account:wallet_finished:Finished loading wallet
DEBUG:account:wallet_finished:All wallets loaded
DEBUG:account:wallet_finished:Finished loading wallet
DEBUG:account:wallet_finished:All wallets loaded
DEBUG:toast:display:NOTIFY DISPLAY
DEBUG:network:pop_discovery_stack:New node found : G3wQw
```

**Comment by M5oul** [comment]
Nice.
Fixed for me with https://github.com/duniter/duniter-python-api/commit/6ead396a5d3f12dcd58317601f593b80c4e46438.

It is fixed for you @JeanFe, @c-geek, @vtexier with [v0.20.9](https://github.com/duniter/sakia/releases/tag/0.20.9)?

**Comment by Insoleet** [comment]
I failed my release. It will be done in 0.20.10. Sorry !
