### ISSUE TITLE
Refactor backend

### ISSUE THREAD

**Issue by Insoleet** [duniter/sakia#517]
Currently the backend suffers many limitations : 
- The business layer is too big and does too many things
- No data layer

**Comment by Insoleet** [comment]
We need a Data layer and an Network layer.

The Network layer would : 
- Give access to external modules, one for BMA, one for a Graph API, etc...
This can be based on existing network layer. But this layer needs a lot of optimizations.

It should be possible to know if a module is accessible or not.

The Data layer would : 
- Create a layer for Sakia Entities, based on SQLite

**Comment by Insoleet** [comment]
I'm wondering two things about the data layer : 

- Should we use an ORM ? Intuitively I'd say no, there things are mostly annoying.
- Should we use SQLite or simple json files ?

I think we should go for a repository pattern. That means, having : 
- Simple Domain Model classes, probably built using `attr` module
- Repository classes, used to create, update, drop data from the SQLite / Json files

**Comment by vtexier** [comment]
Yes, by experience, I am fed up with ORM.
ORM got a very attractive code for tutorials or demo, but is an overload in everyday performance.
Everyday I try to avoid ORM commands and even objects. Array resultSet are often enough, lighweight and fast.

So we can imitate ORM with entity classes and repository classes using clean DB driver like http://docs.python-guide.org/en/latest/scenarios/db/

**Comment by Insoleet** [comment]
We could use for example `https://github.com/mkleehammer/pyodbc` 

There is also https://github.com/aio-libs/aioodbc but I wonder what is the performance cost of such a library. It says it's using thread so maybe the cost isn't that high !

**Comment by Insoleet** [comment]
### General thoughts : 

Data which does not change **if no rollback happens** : 
- Identities published on the network
- Past transactions

Data which can change :
- Identities can become "Revoked"
- Latest membership document published
- List of published certifications (it can grow, but not valid anymore certifications can be dumped from Sakia db naturally without requesting the network

There are two ways to handle the data which can change : 
- On Sakia startup : refresh state of our identity, our membership, and our certifications received
- During Sakia run : when we receive a block, we can feed our data and we do not need to request the network. 

This means that we can reduce a lot the requests done to the network. We can display identities in the WoT and in the Transactions tab without any need to request the network.

I suggest that for data not available locally, every item could start their own async task to refresh themselves. They would then send a signal to say "My data changed, you should refresh what you are displaying about me". For this, we need services responsible of displayed entities. These services would be able to start background task so that the GUI does not suffer from background asyncio.

### New backend architecture proposal 
 
This need what we know have the following modules : 

- Data module : This module would handle sakia entities. 
  - This entities are simple objects containing attributes. No intelligence involved here.
  - The entities are at least the following objects : `Identity`, `Certification`, `Transaction`
  - The memberships state is part of the Identity object.
  - Blockchain timestamps are part of the objects. We do not need to request the blockchain anymore to get the time.
  - Sakia should also bring the entities `Community`, `Node`, `Key`, `Parameters`
  - The Community handles informations about a given Community : the currency, the monetary mass, the number of members. It also has attributes needed to compute next dividends... The attributes saved here should be used to reduce the number of requests.
  - The Key is a couple of (pubkey, salt). 
  - The repositories are objects which have the ability to load, update and drop data locally.

- Service module
  - The `ProfileService` handles the parameters or the profile (Entities : Parameters)
  - The `ConnectionService` is responsible of the Community
  - `AccountService` to build and sign user documents. It does not broadcast them. (Entities : Key)
  - `TxHistory` service to refresh user transactions (Entities : Transaction)
  - `RegistryService` which handles Identities discovery and refreshing (Entities : Identity, Certification)
  - The `NetworkService` is used to discover the network. (Entities : Nodes)
  - The `BMAService` is used to request BMA API. It's really near to what is currently implemented in `BmaAccess`. But we should reduce the cache a lot. A logic should be implemented to clear old informations from the cache. (Entities : None, the service is fed by nodes bma endpoints)

The Application class, which is like a `God mode` class, would be removed and dispatched in existing services. The instanciation of sakia would instanciate the Main Window and feed it with the services.

I would love to have opinions of experienced developers on this topic.

**Comment by c-geek** [comment]
I agree with both of you about ORM: you don't need it, *at all*.

Also, for what my opnion worths and, given the fact I do not plan to take part with Sakia code but *ponctually*, here it is:

* I like the Database (DB) idea. I personnally see it as a cache system, a part of it.
* Sakia services always query the cache (the DB).
* Sometimes, the DB doesn't have the required data. In such case, the Data module will call the Network module to feed the DB.
* Sometimes, a dedicated service detects a blockchain rollback and invalidates part of the data in the DB. In such case, the data is deleted, which makes Sakia loop on Data retrieval procedure when needed.
* The network data might be part of the Data module, but but it may behave a bit differently than just pull-the-network since it can use WebSockets push events.

I don't know if this is clear, but my opinon is you should clearly separate the data access from the medium, physical underlying system. This is the Data module's role to decide wether it should cache the network data (transactions, blocks, ...) in a cache or not, and you should not have anything in services caring about the technical difficulties to access this data.

Of course, you do understand that functionalities like "I want to display all the sources ever written in the blockchain" would have a huge data access, no matter how performant is the Data layer.

And I think what you imagined is already in this direction I'm describing.

**Comment by c-geek** [comment]
I repeat: if you don't like / don't understand what I've said and better understand other propositions, then just develop those other propositions! I'm just giving my opinion because inso asked me to do so.

**Comment by Insoleet** [comment]
Thanks a lot for giving your opinion @c-geek. It helps a lot to see what I missed ;)

I'm not confident about the data layer being able to request data to the network. In my mind, the data layer was a classic layer to store and read data locally.  
Services were able to update data in the DB and ask the network for the data if it was not available.

But maybe we need another module dedicated to this, between services and data ? Like a "proxy" module containing proxy classes based on "proxy pattern".

This would do something like : 
GUI -> Services -> Proxies -> Data or Network
The proxy would check if the data is available locally. If it is, it updates it. If it is not, it does a lookup on the network. 
It would return an data object with default values in the meantime. The question is, which mechanism should be used to refresh the GUI when the data was obtained ?
I think a signal could be send from the data object to mean that its content was refreshed.

What do you think about it ? @c-geek , @vtexier ? I fear the signal mechanism could be come rather complex, but I also thinks it would be the best from a performance point of view. Less asyncio when it is unneeded.

**Comment by c-geek** [comment]
Yes this is exactly what I mean, the only difference is that you move the logic dedicated to Network retrieval in the Proxy module instead of having it shared in the Data module. That's fine, it is even better.

However, I do not understand the: `It would return an data object with default values in the meantime.`

Why do you want to give false informations? The user can wait, I think.

**Comment by Insoleet** [comment]
For example, when a relative value is computed, we need to request the network for the dividend.

I think, a default behaviour would be : lets compute the relative value with latest UD generated, while we refresh the UD in the background for the next relative value computations.

**Comment by Insoleet** [comment]
Here is a probably the target UML then ! 

![backend](https://cloud.githubusercontent.com/assets/1170293/17979244/e7d8887e-6af9-11e6-80e4-44ddf1280f8e.png)

**Comment by Insoleet** [comment]
One question remains on the implementation of the Access layer.

Should we implement it like this : 

```python
class StuffAccess:
    async def get_stuff()
```` 

Which implies to use `await stuff_access.get_stuff()` everytime we want to get data, even if we already have it locally.

Maye we should implement it like this : 
```python
class StufAccess
     def get_stuff()
     async def find_stuff()
```

Which let us use it this way : 

```python
stuff = stuff_access.get_stuff()
if not stuff:
    stuff = await stuff_access.find_stuff()
```

Which reduces the asyncio loop calls needed to get stuff once we already have it locally.

What do you think about it ?

**Comment by vtexier** [comment]
UML diagram is amazing and need to be analyze !

For the previous optimization, I think it is a lot of code only triggered if the cache is empty, which will be the case only at the first install of Sakia... Don't think it is very useful.

I propose a service worker per money, which can be launch like that :

- Run sync from block-chain once by polling and pause.
- Start forever listener with web-socket or/polling.

The worker updates the DB with aggregated data that can support rollback.

Then every service can use the DB without worrying about data freshness.

**Comment by Insoleet** [comment]
Ok I agree with you. I would just add the following description : 

- If the GUI has to lookup for data (example : lookup of text "Ga"), it will start an asynchronous service call. The asynchronous task should lookup for the data, save it when necessary in the database, and return only DB objects.

This way the GUI only has relations with the services and the DB objects.

So the general role of the modules would be : 
- Views : UI layer
- Controllers : Handle application behaviour and user events coming from the view
- Models : Abstraction layer between the view and the DB objects
- Services : General business task involving some logic
- Access : Get data from DB, or execute lookups which will save data in the DB and returns DB objects
- Entities : Raw objects containing only attributes and zero logic

**Comment by vtexier** [comment]
Very good.

In MVC, Model include business logic (services) and data.

So we have : 

* Views : UI layer
* Controllers : Handle application behaviour and user events coming from the view
* Models : Abstraction layer between the view and the DB objects
 * Services : General business task involving some logic. Handles first refresh of the data during the startup of the application, and handle events coming from the network to update data.
  * Access : Get data from DB, or execute lookups which will save data in the DB and returns DB objects
  * Entities : Raw objects containing only attributes and zero logic

**Comment by Insoleet** [comment]
I think this is a good description of the target architecture. I would just add the following, based on this paper : http://ceur-ws.org/Vol-610/paper11.pdf

I am thinking about having 3 layers in the application : 
- Application, built on HMVC approach. Every widget/component of the GUI is built on a triad composed of a dedicated View/Controller/Model. You can see what it looks like in the branch feature/agent_architecture (which is not about agents but components but well...)
- Services
- Data

Like in the following diagram, written in speed : 

![rect4136](https://cloud.githubusercontent.com/assets/1170293/18231800/b21465c0-72c2-11e6-9a92-c0fb55314db7.png)

The main advantage I see is that the general Application behaviour would not suffer much changes from the underlying Services and Data modifications. The triads describe the behaviour of the widgets, but they do not do anything by themselves on the data. The front (Application layer) is heavily decoupled from the back (Services + Data).

**Comment by Insoleet** [comment]
Ok so I implemented the Identity Entity with its Repo. Please check it out and tell me if that seems the right thing to do ! https://github.com/duniter/sakia/commit/0bd0a9e5d56dd2678516ec6a7ed551f09801c72a

**Comment by c-geek** [comment]
I can see the entity carries its table creation in the `prepare` function.

If you ever have the occasion, since you go to SQLite DB, you should really use a "meta_table" which gives you informations about the current version of your database.

This way, you can handle incremental SQL scripts to upgrade the DB on each version without requiring the user to delete its database: the software can apply *just what the user needs* to have its database compliant with the software. And you could move the "CREATE TABLE" to this specific place like I do for Duniter: [MetaDAL](https://github.com/duniter/duniter/blob/1f297c6509385c4dab56ac9bc8423abbe0db0cd1/app/lib/dal/sqliteDAL/MetaDAL.js#L32-L160).

**Comment by Insoleet** [comment]
Very good idea indeed. I shamelessly copied your work in the following commit : 
https://github.com/duniter/sakia/commit/142cd2a9ff2602067eb887693606ad20b1f0b0c7

The only difference is that I consider that it's the role of the Meta Database to initialize every tables. The repositories only handles selects, updates, drops and inserts.

Also, please note that this implementation depends on my pull request to the attr project ( https://github.com/hynek/attrs/pull/78 )

**Comment by Insoleet** [comment]
Very good idea indeed. I shamelessly copied your work in the following commit : 
https://github.com/duniter/sakia/commit/142cd2a9ff2602067eb887693606ad20b1f0b0c7

The only difference is that I consider that it's the role of the Meta Database to initialize every tables. The repositories only handles selects, updates, drops and inserts.

Also, please note that this implementation depends on my pull request to the attr project ( https://github.com/hynek/attrs/pull/78 )

**Comment by Insoleet** [comment]
Back to the implementation of the `Access` layer. 
 - Since we want the UI to directly request the DB, the UI should use the access layer with synchronous methods.
 - For the Service, they will request the network. They should use the access layer with asynchronous methods.

So we need to implement the access layer like this : 

```python
class StufAccess
# returns None if local data is not present
     def get_stuff():
          pass
# try to find stuff using the network
     async def find_stuff():
          pass
```

> 
> I propose a service worker per money, which can be launch like that :
> 
>     Run sync from block-chain once by polling and pause.
>     Start forever listener with web-socket or/polling.
>

**Comment by vtexier** [comment]
To handle database migrations, I use a simple java command-line tool named "flyway".
You write changes in sql files. It handles versions in a dedicated table.
Can give some ideas : https://flywaydb.org/

**Comment by Insoleet** [comment]
Interesting, thanks for the link.

Thinking back to the `Access` classes, I don't like very much their names.
Looking in some android architecture, I found some `Processor` components which look like what we need here : 
![2016-09-08 10_44_59-android-developing-restful-android-apps pdf](https://cloud.githubusercontent.com/assets/1170293/18348248/8ee9a816-75ca-11e6-8599-4bbb6c383115.png)

So I think all `IdentityAccess`, `BlockAccess` etc... should be named `IdentityProcessor`, `BlockProcessor`...

For the API Accesses, I suggest to rename them `Connectors`. We would then have `BmaConnector` and `ESConnector`.

What do you think ?

**Comment by vtexier** [comment]
Yes,  Processor and Connector are explicit names.
I wonder if we really need to have two names, one for the DB and one for the network.
Abstraction layers take care of how to retrieve data without the need to see it in the name.
Except if the developer need to call Processor and Connector differently (sync or async).

**Comment by Insoleet** [comment]
I think Connector should be at a lower layer than Processor.

For me it would be like this : 
Services <-> Processors <-> Repositories and Connectors

**Comment by vtexier** [comment]
Even better !

**Comment by Insoleet** [comment]
Here you go ! 

https://github.com/duniter/sakia/commit/3a9c7831ae5f6b09833efdbeb5cf997a93d165df

I really like they way things are going. I think we can start to develop the data layer. Would you like to participate, vit ? If so, just tell me which entity handling you develop so that we do not do any conflict !

Here is the UML, it has been updated in the repository : 
![backend](https://cloud.githubusercontent.com/assets/1170293/18376476/db86f440-765f-11e6-8d13-eebb9b66b578.png)

**Comment by vtexier** [comment]
I'll be pleased to help. If you've done one entity that I can use as an example, assign me the easiest ones. And if you go faster than me, re assign the issue you take back to alert me.

**Comment by Insoleet** [comment]
I implemented the Entity, its Processor and its Repo in the `data` module of the branch feature/backend : https://github.com/duniter/sakia/tree/feature/backend/src/sakia/data 

I moved the `BmaAccess` class to the connector `BmaConnector`. I removed caching features from it at the moment.

Please be sure to use my pull request for `attrs` to be able to use `astuple` method ( https://github.com/hynek/attrs/pull/78 )

Some informations about what is also missing : 

- Tests : Currently there is only a unittest for the Repository. I'd love to add some tests for Processors too.
- Services : I didn't start to implement the services yet. I think we should first develop the lower layers. 

At first, I think you could implement Community and Blockchain entities. They contains informations you are used to handle for the Informations tab !

**Comment by Insoleet** [comment]
Thanks a lot for your PR @vtexier  !

I see two possibilites from now on if you wish to continue ! 

 - You can implement other entities
 - You can try to implement the services for the Blockchain and Community entities and use them in Sakia. I think it would be really useful to see how this would integrate finally integrate from a pure coding point of view !

**Comment by vtexier** [comment]
For me, blockchain and community should be merged as they reflect only one currency.
Except if you want to separate immutable attributes (block0 parameters) in community and dynamic attributes in blockchain.

As you can see I get rid of two primary keys cause I only need the currency id/name to get the blockchain/community infos.

I will try to understand where and when you get community info from peers to populate the db.

**Comment by Insoleet** [comment]
> Except if you want to separate immutable attributes (block0 parameters) in community and dynamic attributes in blockchain.

I think it is interesting to separate those two, exactly because of this, yes. 

As you can see I get rid of two primary keys cause I only need the currency id/name to get the blockchain/community infos.

> I will try to understand where and when you get community info from peers to populate the db.

I think we only have to develop  a method to populate the DB based when we add the community for the first time. This is kind of easy.
For this, I was planning on implementing a `NodeProcessor` which would be the accessor to the nodes we discovered. Thus, this needs to implement at first the `Node` entity...
The `NodeProcessor` be feeded by a `NetworkService` which is not needed right now (in the tests we can just populate the `NodeProcessor` with a mocked node like in current functional tests.)

**Comment by Insoleet** [comment]
I pushed my implementation of the Node entity. I totally forgot that it was up to you ^^ I hope you didn't start to work on it yet !

**Comment by vtexier** [comment]
pfff, you take my job ! ;)
No I wasn't, I will re-factor block-chain/community and I will tell you what entity I'll do next.

**Comment by Insoleet** [comment]
For your information, I'm currently developing the Node processor and Network service. So that we dont work on the same subjects ;)
