### ISSUE TITLE
0.30.5 Sakia 0.20.5

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#523]
Je fais tourner Duniter 0.30.5 Cesium semble ne pas marcher du tout (pas de récup de données...) et sur Sakia problèmes d'ergonomies, j'ai dû envoyer 4 transactions au lieu d'une... à cause d'un message d'erreur semble-t-il, qui au final ne semble pas un message d'erreur. On manque de retour sur Sakia après une transaction, et il est dangereux de ne pas demander confirmation par password, de laisser la fenêtre de transaction ouverte, de ne pas mettre à jour le compte. Apparemment mon compte marque toujours 10,879 DU alors que j'ai envoyé 4 transactions de 2 x 4,75 DU et 2x4 DU. Dangereux Sakia ! :)

**Comment by M5oul** [comment]
[Sakia 0.20.7 gère le protocole 0.3](https://github.com/duniter/sakia/releases).
