### ISSUE TITLE
On initial synchronization, the the transaction list is empty

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#528]
Easy to reproduce: delete your %APPDATA%/sakia folder, connect with an existing  member account (which has produced money/received  transactions) and wait until the loading bar has finished.

You can see your balance, but not the transaction list which is empty. Maybe because of the filtering dates which are at year 2000.

**Comment by c-geek** [comment]
Note that, after restarting Sakia, the transactions appear.

**Comment by Insoleet** [comment]
Did you try to change the filtering date to see what would occur ?

**Comment by c-geek** [comment]
It shows the transactions :-) Could Sakia put the upper date to today, on startup?

**Comment by Insoleet** [comment]
The date depends on the blockchain time, which probably timeouts during the first startup ;)

Such problems will be fixed hopefully in next architecture.
