### ISSUE TITLE
Version portable ... ?

### ISSUE THREAD

**Issue by vincentux** [duniter/sakia#531]
Bon c'est clairement pas une priorité, 
mais est-ce compliqué a mettre en place une version portable de Sakia ? _(et est-ce vraiment utile ?)_
http://portableapps.com/development

**Comment by M5oul** [comment]
Tu veux dire ordinateur portable mobile ?
Ça me semble pas très envisageable de porter du Python, Qt sur mobile.
Césium le fait déjà très bien.
De plus ça n’est pas la priorité de Sakia.

**Comment by vincentux** [comment]
Je pensais surtout "portable" dans le sens de l'installer sur clé usb ...

**Comment by M5oul** [comment]
Ok, je connaissait pas.

**Comment by vincentux** [comment]
J'utilise PuTTY et Firefox portable pour ne rien n'installer sur le pc du boulot ;)

**Comment by Insoleet** [comment]
Sakia est déja portable, il suffit de télécharger le .zip !
