### ISSUE TITLE
Shouldn't sakia notify new transaction reveived only when fully confirmed?

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#534]
I received a notification for a transaction confirmed at `0/6`.
Shouldn't sakia notify when it's fully confirmed?

Or, sakia could notify for a received transaction at `0/6` and for a confirmed transaction at `6/6`.
With settings to modify behaviour.

**Comment by Insoleet** [comment]
I think a transaction received at 0/6 can already be announced.
