### ISSUE TITLE
Sakia missing information !?

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#538]
Sakia doesn't give the information about the fact one new member who received certifications is really a member or not (for instance due to distance > stepmax) study [this forum line to obtain one case in test-net](https://forum.duniter.org/t/demande-dadhesion-envoyee-en-attente-dacceptation/1309).

It seems in that case that Cesium give 2 valid certificatons, but Sakia doesn't give any about certification neither why the member is not accepted.

**Comment by Insoleet** [comment]
Fixed in 0.30.
