### ISSUE TITLE
Identity expiration should be 6 months in TestNet, not 1 year

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#543]
I was investing about @vincentux being excluded from the currency using Sakia, here is my tool:

![image](https://cloud.githubusercontent.com/assets/969136/20095728/f8f115d0-a5a6-11e6-94a1-5ae6dd11eabc.png)

We can see he renewed on 2016-05-05, yet he was kicked on [block 52234](http://cgeek.fr:9330/blockchain/block/52234), which is the 2016-11-04, not 2017-05-06. That's normal he was kicked after 6 months usage, because the exclusion occurs 6 months after the last renewal in TestNet. Sakia well knows it:

![image](https://cloud.githubusercontent.com/assets/969136/20095943/f1f798fc-a5a7-11e6-9b91-1144adad9255.png)

Maybe the label is not correct, and should be "Definitive expiration". It could also be added a column "Expiration" displaying 2016-11-06 instead of 2017-05-06.

It seems there is also a little offset in the days, since Sakia displays "06" as the day of month whereas vincentux was kicked on the 4th of November. But maybe DUP is not clear about that.

**Comment by M5oul** [comment]
May be an issue here too:
