### ISSUE TITLE
R0 TN incorrect

### ISSUE THREAD

**Issue by gerard94** [duniter/sakia#544]
I think that the formula for Relat Z-sum is incorrect in Sakia:

R0 = (R / UD(t)) - ((M(t-1) / N(t)) / UD(t))

It rather should be:

R0 = (Q / UD(t)) - ((M(t-1) / N(t)) / UD(t))

And the absolute value of the balance in R0 TN unit is too big by a factor one million.

**Comment by vtexier** [comment]
fixed in ec78907cd4003185dede51a7a9d7000262cad318
