### ISSUE TITLE
Hairpinning workaround

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#545]
As may have heard, we have an [hairpinning issue with Sakia](https://forum.duniter.org/t/duniter-reconfiguration-and-network-nat-hairpinning-and-ipv6/1392). Concretely, someone who install both Sakia and Duniter on the same computer **cannot see its node**, whereas people on the Internet can.

Here is a proposal: first, Sakia should first try to contact a node using its IPv6 and fallback to IPv4 if IPv6 fails, because IPv6 solves the hairpinning issue.

Second, Sakia could make an exception about IPv4: it could know its public IPv4 (for example using [python UPnP library](http://stackoverflow.com/questions/22552147/upnp-library-for-python)) and when matching a node declaring the same IPv4, replace the public IPv4 address with the local one.

For example a node with IP 192.168.1.20 declaring:

    88.125.24.32 10300

Should be contacted by Sakia using IP 192.168.1.20, not 88.125.24.32. Of course in this example, Sakia is also running on host 192.168.1.20.

If Sakia was on 192.168.1.30, it should have tried to contact the peer on 192.168.1.30. But if the node is running on 192.168.1.20, it finally would have failed.

**Comment by c-geek** [comment]
Or even better: it could make the mapping by listing the Duniter UPnP opened ports. Because you can obtain the list of UPnP redirections and they can be classed with a name, for example "duniter:upnp".

Example:

	$ upnpc -l
	[...]
	 i protocol exPort->inAddr:inPort description remoteHost leaseTime
	 0 TCP 10200->192.168.1.23:10200 'duniter:upnp' '' 454
	 1 TCP 10201->192.168.1.23:10200 'libminiupnpc' '' 0
	GetGenericPortMappingEntry() returned 713 (SpecifiedArrayIndexInvalid)

You can do this easily using the above python library.

I have to make the new UPnP classification first. https://github.com/duniter/duniter/issues/711

**Comment by c-geek** [comment]
Example of Livebox UPnP display, with duniter/duniter#711 fixed:

![image](https://cloud.githubusercontent.com/assets/969136/20238101/a2b74988-a8e3-11e6-9df0-c69293ecc476.png)

**Comment by Insoleet** [comment]
Since ipv6 fixes the problem and because ipv4 is depreciated, I will only implement the ipv6 first.
