### ISSUE TITLE
Transactions are not sorted by their amounts

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#549]
On transactions tab, sorting transactions by their amounts don't sort them.
It happen using `UD` and `units` benchmarks.
This is string types sorting which gives strange sorting.
The sort must could be done all benchmarks or only with `units` one.
The sorting must be on integer types.

![sakia_transaction_tab_sort_amount](https://cloud.githubusercontent.com/assets/4758871/20618576/2a8cd0ec-b2f0-11e6-9aaf-ca3a0f3f24e5.png)

I found this problem searching for the transaction with the biggest amount I received.

**Comment by Insoleet** [comment]
Nice catch. Once I release a stable version of Sakia 0.30, I'll clean up the tickets list to see what will be done, what will be forget, and what is fixed natively by sakia 0.30.
