### ISSUE TITLE
sakia 0.30 retours

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#551]
Au démarrage il n'y a pas de noeuds par défaut, ce serait pourtant bien. emule fonctionne ainsi : un fichier de noeuds par défaut est livré dans l'install, et se met à jour lors de l'utilisation.

Une vérification ensuite sur X noeuds donnant des résultats corrélés permettra aux démarrages suivants de s'assurer d'être en possession d'une bonne liste de noeuds connectés et cohérents entre eux (évitant ainsi de se connecter sur un faux réseau).

Key / password : la Key devrait être cryptée et invisible à la saisie comme le password (là c'est en clair !)

L'affichage des unités est bien plus clair. Toutefois je vois des UD sur 6 (4,2), je ne sais pas si ça correspond à un calcul sur "c" bien choisi ou quoi d'autre...

Sur transfert money : j'ai du mal à m'habituer à la fenêtre supplémentaire de saisie du password. Pourquoi ne pas demander dans la fenêtre même de transfert la saisie en double (toujours demander confirmation) du password directement et ainsi éviter un empilement de fenêtres ?

De manière générale je trouve que le menu de gauche est chouette et que tous les autres menus (boutons du haut + liste déroulante) devraient s'y trouver. Une seule ergonomie de menu me semble bien plus simple et claire à gérer, sinon ça fait bizarre tout de même (menu gauche, boutons hauts, menu déroulant en haut droite, beaucoup de dispersions superflues, simplifions !).

Inutile de rappeler la base 10⁹ partout, la noter une fois quelque part (pas forcément au niveau du solde d'ailleurs) sera suffisant. Dans tous les cas "x10⁹" n'est pas joli et ".10⁹" est plus standard.

**Comment by Insoleet** [comment]
Merci pour tes retours.

> Au démarrage il n'y a pas de noeuds par défaut, ce serait pourtant bien. emule fonctionne ainsi : un fichier de noeuds par défaut est livré dans l'install, et se met à jour lors de l'utilisation.

Excellente idée, dorénavant, plus besoin d'entrer la moindre adresse de noeud. On utilise les noeuds "root" de la monnaie.

> Key / password : la Key devrait être cryptée et invisible à la saisie comme le password (là c'est en clair !)

Oui

> L'affichage des unités est bien plus clair. Toutefois je vois des UD sur 6 (4,2), je ne sais pas si ça correspond à un calcul sur "c" bien choisi ou quoi d'autre...

C'était un bug.

> Sur transfert money : j'ai du mal à m'habituer à la fenêtre supplémentaire de saisie du password. Pourquoi ne pas demander dans la fenêtre même de transfert la saisie en double (toujours demander confirmation) du password directement et ainsi éviter un empilement de fenêtres ?

Mmmh pourquoi pas oui. Je note pour la beta suivante.

> De manière générale je trouve que le menu de gauche est chouette et que tous les autres menus (boutons du haut + liste déroulante) devraient s'y trouver. Une seule ergonomie de menu me semble bien plus simple et claire à gérer, sinon ça fait bizarre tout de même (menu gauche, boutons hauts, menu déroulant en haut droite, beaucoup de dispersions superflues, simplifions !).

Je préfère quand même séparer l'aspect "navigation" (menu de gauche) des "actions" (menu du haut). Et puis c'est cohérent avec Thunderbird qui m'a inspiré pour cette UI.

> Inutile de rappeler la base 10⁹ partout, la noter une fois quelque part (pas forcément au niveau du solde d'ailleurs) sera suffisant. Dans tous les cas "x10⁹" n'est pas joli et ".10⁹" est plus standard.

C'est corrigé.
