### ISSUE TITLE
Sakia 0.30beta2 feedback

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#552]
(french)

1. Bug sur la liste des mouvements
> Faire un clic droit sur un mouvement (DU, envoi de monnaie, réception) provoque une erreur : 
![image](https://cloud.githubusercontent.com/assets/969136/21962457/ee4c9a5e-db26-11e6-99f7-e6746b272ea1.png)

2. Liste des mouvements : ne pas afficher l'unité de base (x10^y)
> Personnellement, je n'afficherais pas le `x10³` à chaque ligne étant donné qu'il est déjà présent dans le titre de la colonne.
![image](https://cloud.githubusercontent.com/assets/969136/21962497/901b0f32-db27-11e6-8b21-da02a057a6c6.png)

3. Envoi de monnaie : base du quantitatif
> La base saisie est quantitatif est `x10⁰`, tandis que la base affichée pour le solde est `x10³`. Autant avoir une base commune, soit 10³ soit 10⁰, la base courante me semblant une bonne option (x10³)
![image](https://cloud.githubusercontent.com/assets/969136/21962479/7246f76e-db27-11e6-99eb-bbed87777fb6.png)

**Comment by c-geek** [comment]
4. Position des connexions dans la barre latérale
> J'ai ajouté une 2ème connexion (1 compte sybil pour tester la révocation), mais celui-ci n'est pas positionné sous `Network` (il me semblerait logique qu'il y soit).

![image](https://cloud.githubusercontent.com/assets/969136/21962529/549f638a-db28-11e6-8ddf-c49aa412fe6b.png)

**Comment by c-geek** [comment]
5. Rafraîchissement du statut du compte
> En ajoutant ma 2ème connexion, et suite à sa certification par le compte légitime (c'est super pratique le multiconnexions), le compte sybil est bien devenu membre mais Sakia ne m'affiche pas cette information.

![image](https://cloud.githubusercontent.com/assets/969136/21962576/1a3b1666-db29-11e6-87de-22fdf9ed2130.png)

**Comment by c-geek** [comment]
6. Erreur sur nouveau bloc
> Avec actuellement 2 comptes et 2 nœuds sur le réseau, j'ai très souvent l'erreur suivante : 


	    Task exception was never retrieved
	future: <Task finished coro=<BlockchainService.handle_blockchain_progress() done, defined at sakia/services/blockchain.py:36> exception=TypeError("int() argument must be a string, a bytes-like object or a number, not 'BlockUID'",)>
	    ----
	    Traceback (most recent call last):
	      File "asyncio/tasks.py", line 239, in _step
	    File "sakia/services/blockchain.py", line 49, in handle_blockchain_progress
	    File "sakia/services/identities.py", line 283, in handle_new_blocks
	    File "sakia/services/identities.py", line 273, in parse_block
	    File "sakia/services/identities.py", line 235, in _parse_certifications
	    File "sakia/data/processors/certifications.py", line 71, in create_certification
	    File "<attrs generated init 986fd8d68005efb2bfe7fbd4075432e54f205401>", line 8, in __init__
	    self.written_on = __attr_convert_written_on(written_on)
	    TypeError: int() argument must be a string, a bytes-like object or a number, not 'BlockUID'

**Comment by Insoleet** [comment]
Merci pour tes retours, tout devrait être corrigé dorénavant.

**Comment by c-geek** [comment]
7. Erreur sur nouveau bloc
> Difficile de la voir avant, vu que mon nœud n'envoyait plus de bloc...


	    Task exception was never retrieved
	future: <Task finished coro=<BlockchainService.handle_blockchain_progress() done, defined at sakia/services/blockchain.py:42> exception=UnboundLocalError("local variable 'data_hash' referenced before assignment",)>
	    ----
	    Traceback (most recent call last):
	      File "asyncio/tasks.py", line 239, in _step
	    File "sakia/services/blockchain.py", line 53, in handle_blockchain_progress
	    File "sakia/services/sources.py", line 35, in refresh_sources
	    File "sakia/data/connectors/bma.py", line 227, in get
	    File "sakia/data/connectors/bma.py", line 178, in verified_get
	    UnboundLocalError: local variable 'data_hash' referenced before assignment

**Comment by Insoleet** [comment]
C'est même pas particulièrement lié à la mise à jour des blocs. J'ai oublié un `continue` en cas d'erreur `HTTP_LIMITATION`.

https://github.com/duniter/sakia/blob/master/src/sakia/data/connectors/bma.py#L169

Mwarf :) Merci pour le log !

**Comment by c-geek** [comment]
Le point 5 est toujours présent, mais peut-être que la vue n'est pas actualisée à cause du point 7.

**Comment by Insoleet** [comment]
C'est même plus que certain. Je ferais une release ce midi pour corriger ces 2 problèmes mineurs.

**Comment by c-geek** [comment]
Tout bon pour moi.
