### ISSUE TITLE
0.30 beta4

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#554]
Installé, .config/sakia supprimé

"ne trouve pas l'identité sur le réseau"

Comment peut-il chercher l'identité sur un réseau non-identifié ? J'ai cherché par ailleurs, pas de menu, de case où spécifier le réseau... D'où sort-il donc sa connexion à quel réseau ?

**Comment by Insoleet** [comment]
Sakia se connectera par défaut à la monnaie de production. Pour le moment, c'est sur fakenet. 

Pour se connecter sur test_net, il faut utiliser le paramètre `--currency test_net`

**Comment by Insoleet** [comment]
Jai ajouté une information sur le réseau courant dans la fenêtre de connexion.
