### ISSUE TITLE
Mouvements 1/6 passe directement en 6/6

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#555]
Quand on fait un transfert de monnaie, on commence à voir le mouvement en 0/6, puis habituellement 1/6, 2/6, etc.

Mais là en faisant un transfert inter-comptes (avec un destinataire compte local, donc), le mouvement est directement passé de 0/6 à "6/6" (en fait, le mouvement n'est plus en italique, et le survoler n'affiche plus l'avancement, comme si l'on avait atteint le 6/6 directement).

Or j'ai vérifié la blockchain à ce moment là, j'étais arrivé à 1/6 ou 2/6, mais pas plus.

**Comment by Insoleet** [comment]
Sera corrigé dans la prochaine release, mais nécessitera de supprimer / recréer la connexion.
