### ISSUE TITLE
0.30.0b5 don't have tool bar

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#567]
- Sakia 0.30.0b5:

![sakia0 30 0b5](https://cloud.githubusercontent.com/assets/4758871/22173898/05d259c2-dfd0-11e6-8a34-6b74ed4306cc.png)

**Comment by Insoleet** [comment]
Weird bug. Unfortunately I have no idea where it can come from ? What is your desktop manager ?

**Comment by M5oul** [comment]
It's GNOME 3.22.
Furthermore, I can't right click on node list to set my node as root one.

**Comment by Insoleet** [comment]
It looks like your resolution is huge ? Maybe this is a problem with the screen resolution ?

Do you encounter this bug with other Qt apps ?

**Comment by M5oul** [comment]
Yep, it's a HIDPI screen.
I don't encounter this issue with qBittorrent which might use Qt5.

**Comment by Insoleet** [comment]
Ok maybe the size of the buttons are too small in pixels.

Could you try to modify the .ui files on your desktop to use bigger icons, larger maximum size etc, to check if this is the problem ?

**Comment by Insoleet** [comment]
Oh, and please try this first : 
```
qapp.setAttribute(Qt.AA_EnableHighDpiScaling, True)
```

In setup() method of Application class. ( https://github.com/duniter/sakia/blob/master/src/sakia/app.py#L78 )

**Comment by M5oul** [comment]
I won't be able to try this as there is [this bug first to correct](https://github.com/duniter/sakia/issues/561).
I will see that later.

**Comment by M5oul** [comment]
Problems are still present.
It's may be not linked to Sakia implementation.
It's may be an issue with Qt, HiDPI and GNOME 3.22.

**Comment by Insoleet** [comment]
Is this bug still present ?

**Comment by M5oul** [comment]
Yep.

**Comment by Insoleet** [comment]
Could be fixed in next release, please tell me if it is better on dev branch.

**Comment by M5oul** [comment]
The display is better and buttons arrangement is better.
But, tool bar is still not displayed.

**Comment by Insoleet** [comment]
What do you mean by tool bar then ? Can you take a screenshot ?

**Comment by M5oul** [comment]
I mean `File`, `Edition` etc tool bar.
May be you removed it voluntary.
It's ok, I can play with sakia without it.
I opened this ticket as I don't if it's present on other desktop environment and as this tool bar was present on previous interface on Sakia.

**Comment by Insoleet** [comment]
Aaah :) Well there is no menubar on Sakia since 0.30. I try to keep the UI as lean as possible ! I close this.
