### ISSUE TITLE
Sakia 0.30.0beta9 double result

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#573]
Double result on search ID : 

![sakia](https://cloud.githubusercontent.com/assets/5245398/22220368/b19a311e-e1ae-11e6-8a28-bcf156a71105.png)

**Comment by Insoleet** [comment]
This is totally normal. The identity is not written yet and Pierre Yves published two identity documents. So sakia shows both documents.

**Comment by galuel** [comment]
But how Duniter can hold 2 same UID / pubkeys !???

**Comment by Insoleet** [comment]
As soon as one of Pierre Yves identity documents is written in the blockchain, the other one will disappear.
