### ISSUE TITLE
Sakia 0.30: confusing identity fields

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#575]
Very nice interface now to certify people in one single window.

However, I had to understand that the "password" contained 2 fields, are for secret sentence + password, and not the password to be confirmed 2 times. So it is a little bit unclear...

Ok the texts are in the input fields (didn't seen them first), but the title should not be "password" only, but better : "secret key / password" so it will be clearer.

**Comment by Insoleet** [comment]
Fixed in 0.30.2.
