### ISSUE TITLE
Handle money destruction

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#579]
OK, this is very special case, but it can occur regularly:

![image](https://cloud.githubusercontent.com/assets/969136/22247490/63e650ce-e23a-11e6-9f05-3fbc088ec768.png)

This account has received Ğ0,50, yet it displays Ğ0,00. Sakia is right, the good amount is 0,00.

I want to explain why, and also explain why we need an extra « consume » line justifying the amount 0,00.

> Please note here the bug about the very first line: the `TENGx` key does not receive the UD, I don't know why it's here. We will only consider the `cgeek` line in this bug report, plus the balance `0,00`.

Actually, cgeek tried to send Ğ0,50 to TENGx. But TENGx account is new, and its current balance equals  0,00. With the incoming 0,50, the total amount on the account is Ğ0,50: the protocol stands that an account whose balance is < Ğ1,00 must see its sources destroyed. The account must be cleard out.

Here, we don't see the 0,50 destruction. Adding a line of the destruction would help to understand why after sending 0,50, the account still has a balance of 0,00.

How to know when to add such line?

Consider the all the account's sources, by block inscription order, ascending (oldest first). Start with the very first (oldest) record and then: for each new movement, if the balance is < Ğ1,00, add destruction movements for each unconsumed source. Balance now equals 0,00. Continue.

Example:

	Block# | Amount | Comment
	-------|--------|---------
	    21 |  -0,01 | Chipolata
	    20 |  -5,00 | Party
	    12 |  +6,00 | Birthday
	     7 |  -1,00 | Beer
	     6 |  +0,26 | Sales
	     5 |  +0,30 | Sales
	     4 |  +0,20 | Sales
	     1 |  +1,00 | Gift

	Visual balance: 1,75
	  Real balance: 0,00

What the account would look like with my proposal:

	Block# | Amount | Comment
	-------|--------|---------
	    21 |  -0,99 | Too low balance
	    21 |  -0,01 | Chipolata
	    20 |  -5,00 | Party
	    12 |  +6,00 | Birthday
	     7 |  -0,26 | Too low balance
	     7 |  -0,30 | Too low balance
	     7 |  -0,20 | Too low balance
	     7 |  -1,00 | Beer
	     6 |  +0,26 | Sales
	     5 |  +0,30 | Sales
	     4 |  +0,20 | Sales
	     1 |  +1,00 | Gift

	Visual balance: 0,00
	  Real balance: 0,00

**Comment by Insoleet** [comment]
For money destruction, does it happen when you own less than 100 in current base ?

**Comment by c-geek** [comment]
Exactly.

**Comment by Insoleet** [comment]
Ok this is going to be implemented in next release :)

**Comment by Insoleet** [comment]
One question : are the sources destroyed after parsing new block, or before ?

**Comment by c-geek** [comment]
After. So if a new block transfers `50` to a new account `A`, we will have in Duniter database:

* a new record crediting `50` to `A`, when parsing the block
* a new record debiting `50` from `A`, at the end of the block parsing
