### ISSUE TITLE
Sakia freeze on new block with a transaction in it

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#580]
Sakia get often stuck, I guess it is on a new block arrival when a transaction for us is included in it.

**Comment by Insoleet** [comment]
Can you get some logs when it freezes please ? And a use case that I could try to reproduce ?

**Comment by c-geek** [comment]
http://paste.twiced.fr/vadoreredi.sm

However I don't see any error in the logs.

Use case: have several connections in your Sakia account (1 member + 1 non-member) and transfer money between them. Sakia has bugged for me both on sending + on block receival.

However, the transaction is well sent and written by the nodes.

**Comment by Insoleet** [comment]
After restart does the transaction appears correctly in the table ?

**Comment by c-geek** [comment]
Yes.

**Comment by Insoleet** [comment]
I can't reproduce. What can of freeze is this ? Do you need to kill Sakia process ?

**Comment by M5oul** [comment]
I also experimented this bug.
The freeze stuck sakia, and my manager ask me to wait or to kill Sakia process.

**Comment by Insoleet** [comment]
Does Sakia wake up after some time ?

**Comment by M5oul** [comment]
Yep, if I remember well.
I have to test more.

**Comment by c-geek** [comment]
I just launched Sakia after a night off, and the freeze appears after few seconds (on network refresh).

I will wait to see if it unfreezes.

**Comment by c-geek** [comment]
Still freezing.

**Comment by c-geek** [comment]
I can continue for until an hour, but I guess it won't change anything :confused:

**Comment by Insoleet** [comment]
Yes, can you upload your database somewhere so that I can observ what happens with your accounts ?

**Comment by c-geek** [comment]
Sure: https://framadrop.org/r/bVt0tlC_Nh#6Ad2TLYMe8ghYojL7KWcWSHUPxQD8N3USCaFUuHRiTU=

**Comment by c-geek** [comment]
It is now 13h24, and the freeze has not ended. I close Sakia.

**Comment by c-geek** [comment]
Pro tip: if you don't look at network view, Sakia does not freeze.

**Comment by c-geek** [comment]
Maybe this can help:


	    Task exception was never retrieved
	future: <Task finished coro=<BlockchainService.handle_blockchain_progress() done, defined at sakia/services/blockchain.py:52> exception=RuntimeError('coroutine raised StopIteration',)>
	    ----
	    Traceback (most recent call last):
	      File "sakia/services/transactions.py", line 115, in parse_dividends_history
	      StopIteration
	  
	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "asyncio/tasks.py", line 239, in _step
	    File "sakia/services/blockchain.py", line 68, in handle_blockchain_progress
	    File "sakia/services/transactions.py", line 81, in handle_new_blocks
	    RuntimeError: coroutine raised StopIteration

**Comment by Insoleet** [comment]
If never looking at the network view really stops the freezes (wtf btw), I think this is a different error.

But this error is still interesting :)

**Comment by Insoleet** [comment]
Both issues will be fixed in next release.
