### ISSUE TITLE
Recipients are not all listed for transactions with multiple recipients

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#581]
For example [this transaction](http://cgeek.fr:10900/blockchain/block/352) (`REMU:30:39`) sends money to kimamila and I, but this is what I see in Sakia:
 
![image](https://cloud.githubusercontent.com/assets/969136/22253231/10f2eb9a-e251-11e6-890c-5fe914390e7d.png)

**Comment by Insoleet** [comment]
This will need many changes and so is planned for next major release.

**Comment by Insoleet** [comment]
Now I can check that you are not sending money to yourself using Remuniter account 👍 

![image](https://cloud.githubusercontent.com/assets/1170293/23889025/3d7de0a6-088b-11e7-804a-8e93807415b9.png)

**Comment by c-geek** [comment]
Awesome!

**Comment by c-geek** [comment]
I mean: will we be able to add any pubkey in Sakia?!

**Comment by c-geek** [comment]
Because, really, that would be GREAT: when I add a wallet, I don't see any reason why I must type my salt/passwd before I need to sign a transaction.

**Comment by Insoleet** [comment]
Yes you will. You will obviously need the correct scrypt parameters if you want to be able to publish document with this key !
