### ISSUE TITLE
Same identity and same pubkey displayed two times

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#583]
On WoT tab, I search for `matiou`, and I get two results with same pubkey `Aa…`

**Comment by Insoleet** [comment]
The publication block is different, this is not a bug.

![image](https://cloud.githubusercontent.com/assets/1170293/22282094/acf5f472-e2da-11e6-8038-b131ba21237b.png)

**Comment by M5oul** [comment]
May be this issue is due to the fact that two nodes added this new identity on the blockchain at a different moment without verifying if this id already exists.
