### ISSUE TITLE
Sakia says 'moul' is no more member

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#584]
I can't certify people.

![capture du 2017-01-26 19-22-55](https://cloud.githubusercontent.com/assets/4758871/22344608/077fa564-e3fd-11e6-820d-532ea61a5f12.png)

I could generate block which were accepted by the network.

**Comment by Insoleet** [comment]
@c-geek : I define if an identity is a member using following test : 

```
 identity.member = identity_data['membershipExpiresIn'] > 0 and not identity_data['outdistanced']
```

It seems that this is wrong ?

**Comment by M5oul** [comment]
My identity is outdistanced and is still member:
```bash
curl duniter.org:8999/wot/requirements/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
{
  "identities": [
    {
      "pubkey": "J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3",
      "uid": "moul",
      "meta": {
        "timestamp": "0-E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855"
      },
      "expired": false,
      "outdistanced": true,
      "certifications": [
        {
          "from": "7KL2QXXFULDpsQY4UdSr5oEVx6rFE6oxeagRdkCX35bf",
          "to": "J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3",
          "expiresIn": 2261320
        },
        {
          "from": "CFP3oacjwDJARL89D2Gkz6LeMoVAu4ggE65CvqSp9Q9K",
          "to": "J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3",
          "expiresIn": 2261320
        },
        {
          "from": "HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk",
          "to": "J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3",
          "expiresIn": 2261320
        }
      ],
      "membershipPendingExpiresIn": 0,
      "membershipExpiresIn": 2261320
    }
  ]
}⏎
```
My identity will be excluded for membership renewal if this outdistances is not fixed.

**Comment by c-geek** [comment]
@Insoleet 

> It seems that this is wrong ?

Yes, `membershipExpiresIn > 0` is enough I think. Because you can temporarily be outdistanced because of newcomers. You can also check who is under `/wot/members`, that's a sure source.

@M5oul 

> My identity will be excluded for membership renewal if this outdistances is not fixed.

Exactly.

**Comment by Insoleet** [comment]
> Note: you can also check who is under /wot/members, that's a sure source.

Yes but since it is not scalable, I prefer to avoid that.

Ok for membershipExpiresIn in next release.
