### ISSUE TITLE
Bruno problem

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#585]
When looking for "Bruno", I get the following result:

![image](https://cloud.githubusercontent.com/assets/969136/22368286/08b09720-e486-11e6-9846-e0a320e359e6.png)

But if I try to find one of them in the WoT view, I can only check "Bruno" (uppercase), not "bruno" (lowercase).

![image](https://cloud.githubusercontent.com/assets/969136/22368323/347b36f8-e486-11e6-9be6-88de0c75acc8.png)

**Comment by c-geek** [comment]
Btw: right clicking on "Bruno" or "bruno" in the « Identities » view gives me a contextual menu to see him in the WoT view, but the click does not trigger anything. I stay on the « Identities » view.

**Comment by c-geek** [comment]
Interesting: I've made a "Right-click > Informations" on bruno (lowercase), and here is what I get:

![image](https://cloud.githubusercontent.com/assets/969136/22368418/ab5d8a14-e486-11e6-85e4-7d4ba471344a.png)

Note: the popup deals with Bruno (uppercase), but the "Bruno" record turned to red color, bot "bruno" which is the one on which I right clicked.

**Comment by Insoleet** [comment]
Ok on my version I don't reproduce all these problems, only the right click -> view in web of trust. Maybe I fixed a lot of incoherencies in the code since 0.30.2. I'll release asap.
