### ISSUE TITLE
Display who is a sentry and who is not

### ISSUE THREAD

**Issue by Insoleet** [duniter/sakia#587]
This can be detected locally in the client because it depends on issued certifications. 

Also, add details about the WoT in the informations tab.

**Comment by Insoleet** [comment]
With new sentries algorithm, it depends on issued and received certifications.

It means that we have to require cert-by, certs-of and requirements to know if an identity is a sentry or not. It consumes too much resources.

@c-geek : do you think this information could be added to requirements URI without consuming to much nodes resources ?

**Comment by c-geek** [comment]
I think it would be better to have a dedicated URL, to make it simple. You require it once, and you only need to require it again when a new block with either `Joiners`, `Certifications`, `Excluded` has one line or more. Which is not that frequent.

What do you think of this proposal?

**Comment by Insoleet** [comment]
It won't help very much because I don't save locally all the identities, only the ones which are directly connected to the local identity. For all other identities, Sakia requests the network.

So when we search for an identity and look in the web of trust tab, sakia would have to request one more time the sentry url, which is not very good.

**Comment by c-geek** [comment]
But you want to tell "who is sentry and who is not", so if you look for each individual, you will multiply the API calls.

**Comment by Insoleet** [comment]
Yes, but I already need to require the requirements URI to know if an identity is a member or not. So, if the sentry information is present in this uri, I don't need to send another GET.

**Comment by c-geek** [comment]
OK.

**Comment by Insoleet** [comment]
Please note that this is interesting only if it is light for duniter nodes. If it is costly, we should probably just use another API, like the neo4j one.

Also, I forget why we added certifications in the requirements URI. Did we do it to request if an identity is a sentry or not ?

**Comment by Insoleet** [comment]
This field will be added to identities in next release.
