### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by urodelus** [duniter/sakia#593]
With sakia-0.30.3-win64.exe, the version is still indicated "Duniter version v0.20.0a18" in control panel.

**Comment by Insoleet** [comment]
Can you take a screenshot please ?

**Comment by urodelus** [comment]
![sakia0300](https://cloud.githubusercontent.com/assets/16271206/22479755/3d909a50-e7ef-11e6-8e66-c4416b292a4e.jpg)

**Comment by Insoleet** [comment]
Its duniter not sakia, right ?

**Comment by urodelus** [comment]
Oups ! Sorry

**Comment by Insoleet** [comment]
Please report this bug on Duniter tracker ;)
