### ISSUE TITLE
Transaction: 100 lines limitation / money recovering when canceling

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#594]
I tried to send 11 from my `moul` identity to a wallet, and I get following notification `To long transaction` or a message like that.
Finally, the transaction seems sent as it present on both wallets.

**Comment by M5oul** [comment]
After one night, the transaction is not on the blockchain.

**Comment by M5oul** [comment]
I canceled the transaction, now my money is not back. the wallet have 0 UD.

**Comment by Insoleet** [comment]
Interesting bug, thank you for testing !

You can remove the wallet and add it back. It will recover the sources.

**Comment by Insoleet** [comment]
The 100 lines limitation is a future feature of sakia. https://github.com/duniter/sakia/issues/529

**Comment by M5oul** [comment]
I tried again with sakia 0.30.4 and a deleted `~/.conf/sakia` and had same problem, I send 13 UD:

I get the notification about 100 lines and this error log:

```bash
DEBUG:network:handle_change:000052BA70 -> 000052BA70
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<accept() done, defined at sakia/gui/dialogs/transfer/controller.py:130> exception=UnboundLocalError("local variable 'value' referenced before assignment",)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/dialogs/transfer/controller.py", line 149, in accept
  File "sakia/gui/dialogs/transfer/model.py", line 94, in send_money
  File "sakia/services/documents.py", line 375, in send_money
  File "sakia/services/documents.py", line 342, in prepare_tx
  File "sakia/services/documents.py", line 276, in tx_sources
UnboundLocalError: local variable 'value' referenced before assignment
DEBUG:bma:verified_get:Requesting requirements on endpoint BASIC_MERKLED_API duniter2.elois.ifee.fr 5.135.152.75 2001:41d0:8:d24b::1 8999
```

---
Concerning, transaction recovering, it works, but I had to restart Sakia to make it works after canceling the transaction.

**Comment by M5oul** [comment]
Ok, I sent 5 UD and it works.
There might be many sources used when sending ≥ 10 UD which makes a transaction document ≥ 100 lines.

**Comment by Insoleet** [comment]
@blavenie What algorithm did you use finally to handle the 100 lines limitation ?
