### ISSUE TITLE
Sakia 0.30.3 certification tab

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#596]
It is not usefull to use the "search" field in that tab, it is too much since we can search ID in identities or WoT tabs, and then we can certify the one we searched. It is enough, and it will be lighter to not use that field again and again...

I just certified a new one (manolollr), but I have no message from sakia (successfully sent, or something...). And I did it in the WoT tab to find him, and after certification sent, the WoT tab doesn't refresh, I need to do it manually, it would be logical to refresh it after sending a certification...

**Comment by Insoleet** [comment]
Fixed in next release.
