### ISSUE TITLE
Balance of a wallet is not updated

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#599]
I sent 5 UD from my main account to a wallet.

The balance of my main account, changed:

![capture du 2017-02-04 13-23-05](https://cloud.githubusercontent.com/assets/4758871/22618474/576251a8-eadd-11e6-906b-b7e1e670922d.png)

But, not the one of my wallet:

![capture du 2017-02-04 13-22-35](https://cloud.githubusercontent.com/assets/4758871/22618477/5e06b170-eadd-11e6-9332-9e66817740d0.png)

**Comment by Insoleet** [comment]
Will be fixed in next release.
