### ISSUE TITLE
Cannot send money

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#600]
Since Sakia 0.30.4 was released, I completely removed my `.config/sakia/Default Profile/` folder and started Sakia again.

I successfully added my member connection + a wallet.

But for an unknown reason, Sakia does not accept my password:

![image](https://cloud.githubusercontent.com/assets/969136/22619872/19145808-eafe-11e6-935c-142063edb3ad.png)

I've tried to use the simple wallet account as well, but the problem remains. I cannot send money from any account.

**Comment by c-geek** [comment]
Note: I know the screen shows transfer from `HnF` to `HnF`, but that's because I tried to make some changes to see if something happened. But the initial try was from `HnF` to `6Lf` account.

**Comment by Insoleet** [comment]
Weird bug that I canno't reproduce.

Are you sure that you enter secret key + password and not the password twice ? The length look like the same

**Comment by c-geek** [comment]
Nice catch :-) Pff ... I do my dumb user.
