### ISSUE TITLE
Sakia 0.30.7 "no more certifications" !?

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#603]
I tried to certify : 
id : smyds
pk : BjranzuxZUZHdfyqvpUB7u2LYLiNg2aFNhA9FUZAdbqL

With only 11 certifications done at the moment, Sakia let the button in grey with "no more certification" written in it...

I succeeded in certifying it with Cesium...

**Comment by Insoleet** [comment]
Can you share your gtest.db file in your `.config/sakia/Default Profile` ?

**Comment by Insoleet** [comment]
Please let me know if you reproduce it someday.
