### ISSUE TITLE
Sakia take too much CPU when scanning network/nodes

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#613]
Starting with an empty database, sakia takes many times and lots of CPU to discover the network.
It's taking time to sort node. One time that way, one time the other way…

When the db is fill, I sometimes get some big CPU usage.
I prefer to turn off Sakia.

**Comment by Insoleet** [comment]
Can you provide some CPU graph screenshot, to check for the behaviour of sakia ?

**Comment by M5oul** [comment]
I am using `htop`. Sakia sometimes takes 99% CPU of one core which lower my computer performances.

**Comment by M5oul** [comment]
Do I am the only one which encounter this issue?
The issue may come from the Wayland/HiDPI/GNOME/GTK/Qt interactions and network display.
I had a similar issue with GNOME Terminal taking many CPU due to display issue

**Comment by Insoleet** [comment]
I know it consumes a lot of CPU, (25% here).

At the moment, the algorithm is rather stupid : on every node status change, I check the network synchronisation state. So obviously it is costly.

I tried to upgrade the algorithm but it was really buggy, it's not easy to have something robust. I'll try to have something better for 0.31 but I don't promise you anything.

**Comment by M5oul** [comment]
It's much better on 0.31.
Thanks for this fix.
I can let Sakia open now \o/
