### ISSUE TITLE
Nodes are not same color as they have same hash

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#614]

**Comment by Insoleet** [comment]
Could you provide a screenshot and your db file ?

**Comment by M5oul** [comment]
![capture d ecran de 2017-02-26 11-34-08](https://cloud.githubusercontent.com/assets/4758871/23338948/c16bed48-fc17-11e6-8fdb-6fd38852aa8f.png)

**Comment by M5oul** [comment]
- [Here is the database file](https://moul.re/jirafeau/f.php?h=2-oNaUUh&d=1).

**Comment by Insoleet** [comment]
Did you just opened sakia when you saw this error ? I tried to create a unit test to reproduce the error, but I couldn't.

Maybe you just closed sakia when the nodes state were being refreshed ?

**Comment by M5oul** [comment]
If I remember well it happen when running during a moment and not at startup.

>Maybe you just closed sakia when the nodes state were being refreshed ?

Nope.

**Comment by M5oul** [comment]
This one is nice:
![capture d ecran de 2017-03-15 08-40-36](https://cloud.githubusercontent.com/assets/4758871/23938142/59d308b4-095b-11e7-8a3b-27d4e75c6eea.png)

It happen after a database cleanning.
