### ISSUE TITLE
Problem with database lock

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#615]
Sometimes, when I launch Sakia, I get a warning saying sakia is already running.
It happen even if sakia was closed since a long time.
I try again to launch Sakia, and, that time it works fine.

**Comment by Insoleet** [comment]
If you could provide some logs when you close sakia if the lock remains presents, that would be helpful.

**Comment by M5oul** [comment]
Duplicate https://github.com/duniter/sakia/issues/682.
Seems fixed.
