### ISSUE TITLE
cant change language

### ISSUE THREAD

**Issue by Candidesk8** [duniter/sakia#617]
Device : HP pavilion Entertainment PC
OS : Ubuntu 16.10 LTS 64bit
Source : sakia-linux.deb
Version : 0.30.11 

cant change the language
I click on the top right icon with stripes
select settings
every language I choose, it's always in English.

**Comment by M5oul** [comment]
You are right I didn't noticed it!

**Comment by Insoleet** [comment]
Check the Transfer tab. There should be texts translated in this tab.

But the general translation status is not very good with sakia : https://weblate.duniter.org/projects/sakia/i18n/

**Comment by M5oul** [comment]
Yep, in fact.

**Comment by Candidesk8** [comment]
been working a bit on weblate.
still some content to be granted :https://weblate.duniter.org/translate/sakia/i18n/fr/?sid=c06b9a50-fcf4-11e6-b6a7-fa163e69e04a&offset=6#suggestions
