### ISSUE TITLE
informations window

### ISSUE THREAD

**Issue by Candidesk8** [duniter/sakia#619]
when viewing the WoT,
rightlicking a member,
you can select information

![](https://framapic.org/iEj2YbOB3qxu/ZMmiVGczQC8X)

but all information doesn't appear.

if trying to get a bigger window by hand, this is what it give:
![](https://framapic.org/ysneCQDa029O/0YsGiypYXGQL)

how to make the frame adaptable?

**Comment by Insoleet** [comment]
Thanks for the report. Will be fixed in next release.
