### ISSUE TITLE
REMU transactions are not displayed

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#625]
Remunitere transactions are not displayed but it seems they exist on database as the balance is ok:
![capture du 2017-03-09 17-38-22](https://cloud.githubusercontent.com/assets/4758871/23760371/c413594c-04ef-11e7-9fbf-2f8b74adef20.png)

You could see the difference with Cesium:
![capture du 2017-03-09 17-37-53](https://cloud.githubusercontent.com/assets/4758871/23760387/d2c10840-04ef-11e7-811b-f11f28bc192c.png)

**Comment by Insoleet** [comment]
As usual, could you share your .db file ?

**Comment by M5oul** [comment]
https://moul.re/jirafeau/f.php?h=30GNaKOG&d=1

**Comment by Insoleet** [comment]
Indeed they are found by sakia. I'll take a look later, thanks for the report.

**Comment by M5oul** [comment]
That time, after a db refresh, I have all Remu transactions.
