### ISSUE TITLE
Ergonomie du processus d'adhésion

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#628]
Tel que géré dans les clients actuels (Sakia/Cesium) le processus d'adhésion (même que renouvellement) est source de confusions et mène à des incompréhension de ce qu'il faut faire, à la création de doubles comptes en piscine...

Le soucis vient du fait que la génération du document d'adhésion est une simple action de menu alors qu'il devrait proposer un récapitulatif complet dans une fenêtre dédiée, car il suppose des conditions pour fonctionner qui sont la présence de 5 certifications valides (en piscine pour l'adhésion nouvelle, en blockchain pour le renouvellement).

Je propose donc de créer une fenêtre spéciale "dossier d'adhésion / renouvellement" sur la pubkey en cours de consultation, et qui comprend deux parties : 

**Pour la consultation une partie qui comprend :** 

- L'ID
- La pubkey
- L'information qui dit si cette ID est déjà publiée en bockchain ou pas : "Cet utilisateur est déjà un membre inscrit en blockchain" et dans ce cas "est membre, ou n'est plus membre depuis date / heure / n° de block..." ou bien "cet utilisateur n'est pas inscrit en blockchain" => couleurs distinctes ! Vert / Orange / Gris
- La liste une par une des certifications reçues (date / heure / qui, valable jusqu'à date / heure / n° de block...)
- La vérification que les 5 certifications sont bien toutes là, avec un affichage "dossier complet :" check vert "complet" / check rouge "incomplet"
- L'information que le document sera valable jusqu'à telle date/heure (puisque les certifications sont périssables).

**Pour la mise à jour une partie qui comprend :** 

- La saisie de la private key correspondante pour génération du document en local + la possibilité de vérifier ce document texte technique généré, avec un bouton "vérifier le document" qui ouvre le fichier texte, de manière aussi à ce qu'on puisse le transférer sur une machine online si on veut séparer la génération des documents offline de leur envoi online sur des machines distinctes. Procédé qui peut se généraliser à toute génération de documents Duniter.
- Un bouton "publish" qui envoie le document signé à Duniter pour ceux qui voudraient tout faire sur une machine online.

**Note :** _tout client devrait pouvoir importer à part des documents Duniter générés par ailleurs, sur une fenêtre dédiée, qui propose un bouton "publish" pour les envoyer online. Séparer les fonctions de générations de documents et d'envoi online est très importante en terme de sécurité ! Cela évite toute exposition superflue des clés privées contrôlées par les utilisateurs.

Ce procédé améliore aussi la compréhension du mode de fonctionnement de Duniter et la nature des différentes documents qui sont gérés par le protocole monétaire de Duniter._

**Comment by Insoleet** [comment]
These ideas are good but will be postponed to 0.32 because they have a lot of impact on the code.

**Comment by Insoleet** [comment]
I'm going to use the Identity vertical tab to display these informations.

Here is how it looks like for AlexisLecointe for example : 

![image](https://cloud.githubusercontent.com/assets/1170293/25402560/5893855a-29f9-11e7-86a7-b175e3feb0c3.png)

What do you think about it ?

**Comment by Insoleet** [comment]
Should be ok for 0.32.
