### ISSUE TITLE
Sakia ergonomie re-arrangement suggestion

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#633]
List of personnal accounts at left bar is very good we keep it !

Network, Identities, Web of Trust, ğ1 parameters window : are not personal account information, there are general features / information about the money / WoT we are connected in.

Send money and Certification are personal account features they depend of the account from where we want to make the operation...

**So I suggest to keep in left bar :** 

* Remove top network, only personal accounts, replace by "Personal accounts"
* Account ID / pubkey like it is. When clicking on it we have the "UID" window opened (where we don't have the ID ? = strange), and separate Personal account information "ID, balance", money information "name Ğ1, number of members, Monetary mass, Monetary mass per member M/N =" and then personal WoT information Number of members : 59, Certifications received 22 (in WoT range), membership expires in : 361 days... NOT "details" button, that is general information not personal one, we change it of place.
* Transfers window : ok
* Send money : no more popup, but normal window here when clicking in left bar.
* Certification : idem, no popup ! Identity is the one of the personal account we are in + Add an advertisement like this one : https://github.com/duniter/sakia/issues/629#issue-213578749 before showing the Secret key / Password + Possibility to save / load the certification document instead of publishing it direclty, more here : https://github.com/duniter/sakia/issues/628
* Add top level "contact Accounts" where the user will store its pubkey list where he uses to send money to other users. With UID when it's a member, and normal pubkey like in "personnal accounts", so it is the same, just a different list. Theese 2 lists will be available for transactions window.

So you have 1 top level now instead of "Network" : "Personal accounts" and "Contacts accounts"
The user should be able to add a personnal name for each account to remember them easily, just as we do usually for phone and mail contacts. Check https://forum.duniter.org/t/pourquoi-le-compte-client-remuniter-ne-porte-pas-son-nom/2114/5 for more.

**In the top bar the buttons :** 

* Network
* Identities
* Web of Trust
* about WoT : WoT information (we have it in "details" in UID window right now)
* about money : money information (we have it in "details" in UID window right now)

+ All the buttons actions should also be available in the general text menu.

**Comment by Insoleet** [comment]
Ok here is a first draft of my proposal.

The UI looks globally like this : 
![image](https://cloud.githubusercontent.com/assets/1170293/24879730/1274c9b6-1e38-11e7-94da-fbd356880a82.png)

Notice that on the left, the icon of the identity is green if he/she is a member, orange when the membership could expire soon, and red when it is not a member.
Here if you click on "Certify an identity", the certification widget opens just under the button, like for "Details" before.

The send money is transfered to the Transfers menu : 
![image](https://cloud.githubusercontent.com/assets/1170293/24879749/1ef09490-1e38-11e7-8d05-2e40e6aed1e3.png)

The pure wallets don't have access to the certify button.

The top buttons open the view in the center, not as a dialog.

About money and about wot are transfered in the top right menu : 
![image](https://cloud.githubusercontent.com/assets/1170293/24879870/88588262-1e38-11e7-8e67-4a062e43d06c.png)

Is it ok for you ?

**Comment by galuel** [comment]
Yes very nice ! 2 little points : 

a°) In the UID tab (what is "UID" !? a better label should be placed here), information about the account should be placed first, balance 324,52 ğ1 (or UD<sub>ğ1</sub>) / certs received / membership, and general information about the money (M, M/N, total members), only in "about money" and "about web of trust), there are not necessary in specific account information.

b°) In the transfer tab the ğ1 name doesn't appear anywhere... I suggest you put it right to the balance to specify the unit 324,52 ğ1 (or 32,45 UD<sub>ğ1</sub>)

**Comment by c-geek** [comment]
Very nice indeed! The UI becomes more user friendly.

I have only one suggestion: on the « Transfers » tab, could you have the "Send money" button at the same level as the balance? Because there is a lot of empty space there, which consumes the height of the transfers' list.

**Comment by Insoleet** [comment]
> I have only one suggestion: on the « Transfers » tab, could you have the "Send money" button at the same level as the balance?

Yes we can 👍

**Comment by galuel** [comment]
In the same line : 

32,52 ğ1 send money

or

32,52 UD<sub>ğ1</sub> send money
