### ISSUE TITLE
The UD is added to all connections' balance

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#636]
I have wallets in Sakia, and I can see the UD produced on my member account is also present in the balance amount of each wallet. Example:

Member account: 

![image](https://cloud.githubusercontent.com/assets/969136/23904028/c158e0ac-08c6-11e7-9384-2b67a68cb905.png)

Non-member account 1:

![image](https://cloud.githubusercontent.com/assets/969136/23904043/cda9cbe6-08c6-11e7-9c01-2baa01d7c620.png)

Non-member account 2:

![image](https://cloud.githubusercontent.com/assets/969136/23904056/d8d737c4-08c6-11e7-82d3-c458038ec14a.png)

**Comment by M5oul** [comment]
This bug was also on this ticket https://github.com/duniter/sakia/issues/599 where there were two combines bugs.

**Comment by Insoleet** [comment]
I canno't reproduce it. Can you share your db file ?

**Comment by c-geek** [comment]
I can't, I've deleted it. And now I try to reproduce it, but Sakia is crashing on connection add because of "XHX" outputs parsing.

You will have to wait next version ..

**Comment by Insoleet** [comment]
Does any one still reproduce this bug ?

**Comment by c-geek** [comment]
Pour l'instant non, attendons le prochain DU ce midi.

**Comment by M5oul** [comment]
I reproduce it.
On my wallet pubkey `fyqm24NzN7D2Lr4ssrNMacsctymQ2NzBqH9YUYuxSmy`
silkaj says there is `80.0 g1` and Sakia says there is `110.0 g1`.

I cleaned database three days ago, so yes, UD are added on wallet accounts.

**Comment by Insoleet** [comment]
Can you share your g1.db file ? 👍

**Comment by M5oul** [comment]
https://moul.re/jirafeau/f.php?h=1ZvXELWS&d=1
