### ISSUE TITLE
0.30.14 Bad message when "connecting a wallet" + ergonomy

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#643]
When I launch Sakia 0.30.14 for 1st time (./config/sakia deleted before) : 

I asks me to "connect a wallet" (or connect an identity etc...), but this should not be necessary, because I could use it first to check the network, check identities, check WoT views, without "connecting" or "creating" any account in my instance !?

When choosing "connect a wallet" it asks me for "secret phrase / password" that is not necessary (should be an option !?) because I could also copy/paste the pubkey (=RIB in traditionnal bank accounts), without exposing my "secret phrase / password".

After that, then it tells me "congratulations you just published an account, need 5 certifications etc...", but I created this account and put money in it 4 days ago ! This is absolutely not a correct message. This message should only be when "creating a new ID", and not at all when "connecting an account" (and we should be able to connect to member account or simple wallet without any other need than ID or pubkey, and secret phrase / password should be only an option for connect).

**Comment by Insoleet** [comment]
It's a bug. And for connecting with a pubkey, it will come with 0.31.0.

**Comment by galuel** [comment]
Yes !
