### ISSUE TITLE
Sakia 0.31 crashes

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#647]
![sakia](https://cloud.githubusercontent.com/assets/5245398/24569759/041b4e94-1668-11e7-8092-f73992b0c073.png)

**Comment by galuel** [comment]
(sakia:5500): Gtk-WARNING **: Theme parsing error: calendar.css:9:18: 'outline-radius' is not a valid property name
/opt/sakia/base_library.zip/traceback.py:338: RuntimeWarning: coroutine 'get_last_version' was never awaited
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<get_last_version() done, defined at sakia/app.py:191>>
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "sakia/main.py", line 96, in <module>
  File "sakia/app.py", line 88, in startup
  File "sakia/app.py", line 102, in load_profile
  File "sakia/data/repositories/meta.py", line 46, in load_or_init
  File "sakia/data/repositories/meta.py", line 82, in upgrade_database
  File "sakia/data/repositories/meta.py", line 124, in add_sentry_property
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/opt/sakia/sakia/data/repositories/002_add_sentry_property.sql'
Failed to execute script main
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /opt/sakia/sakia.bin

**Comment by vincentux** [comment]
Idem chez moi :/

**Comment by Insoleet** [comment]
Damned, encore un fichier oublié lors de la release ! 

Correction en cours de livraison...

**Comment by Insoleet** [comment]
A télécharger ici : https://github.com/duniter/sakia/releases/tag/0.31.0.post1
