### ISSUE TITLE
Sakia 0.31 impossible to connect anything...

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#649]
Cannot connect with UID : 

![sakia1](https://cloud.githubusercontent.com/assets/5245398/24577424/bbf08d62-16cd-11e7-8988-850f546eb3b3.png)

Cannot connect with pubkey : 

![sakia2](https://cloud.githubusercontent.com/assets/5245398/24577430/cd1a1068-16cd-11e7-88bd-cf0e713180f8.png)

After cancelling any connexion, network view seems to update but nothing in green, all orange : 

![sakia3](https://cloud.githubusercontent.com/assets/5245398/24577431/d2a7bfb2-16cd-11e7-8e82-be716f4e2ab0.png)

Then, trying to connect again to a pubkey, strange apparition of the software GPL licence (it should be in the "about" section of Sakia !? Licence of money should appear perhaps, and/or also in certification process)

![sakia4](https://cloud.githubusercontent.com/assets/5245398/24577437/e7eba2e4-16cd-11e7-9882-558f72a2dbee.png)

**Comment by Insoleet** [comment]
Please share your g1.db file!

**Comment by Insoleet** [comment]
Fixed in 0.31.1
