### ISSUE TITLE
0.31.0 Identity export should not require my passwords

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#650]
@c-geek commented on [Sat Apr 01 2017](https://github.com/duniter/duniter/issues/925)

I've tried to export my identity `cgeek`, and I was surprised that Sakia prompted me my account passwords.

The identity is a public document, and also I've checked the content of the generated file: it is exactly the same as available publicly on the blockchain (and that's correct.. :-) ).

So why asking for the passwords?

**Comment by Insoleet** [comment]
Because the signature is generated "on the fly", no request is made on the blockchain 👍

**Comment by c-geek** [comment]
OK because you have all the identity already recorded. Indeed, I see it in the `identities` table. You even have the identity signature.

So you really don't need to sign it :grin: 

But what about a "pubkey connection"? For instance I type "cgeek" + "2ny7YAdmzReQxAayyJZsyVYwYhVyax2thKcGknmQy5nQ", what will Sakia do? Does it have the full identity in the database?

**Comment by c-geek** [comment]
> Does it have the full identity in the database?

Yes! Really I don't see any reason to ask for the passphrase.

**Comment by Insoleet** [comment]
Ok, you win, I'll find a way to do this cleanly.
