### ISSUE TITLE
0.31.0 Tx operations: lot of empty space

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#652]
@c-geek commented on [Sat Apr 01 2017](https://github.com/duniter/duniter/issues/923)

For example here, I have only 4 transactions with no particularities to display, yet I have a lot of unsued space:

![image](https://cloud.githubusercontent.com/assets/969136/24579063/38b395ae-16ee-11e7-8943-8b1a8293f12d.png)

I suppose it has something to do with multiple-receivers transactions of Remuniter, because for UD or other operations I do not have this problem:

![image](https://cloud.githubusercontent.com/assets/969136/24579078/73dc0436-16ee-11e7-8aab-81401829449d.png)

---

@M5oul commented on [Sat Apr 01 2017](https://github.com/duniter/duniter/issues/923#issuecomment-290919750)

Wrong repository?
I encounter same issue.

---

@Insoleet commented on [Sat Apr 01 2017](https://github.com/duniter/duniter/issues/923#issuecomment-290919789)

Yes I noticed it too. Also if you enlarge the Uid column, the display is much better... Weird.

---

@M5oul commented on [Sat Apr 01 2017](https://github.com/duniter/duniter/issues/923#issuecomment-290919826)

Ah, it's the pubkey which cause the issue.

**Comment by Insoleet** [comment]
Fixed in next release.
