### ISSUE TITLE
0.31.0 Sakia starts with a fully forking network

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#653]
If you start Sakia with no database at all and close the first window, you get this:

![image](https://cloud.githubusercontent.com/assets/969136/24579285/99167412-16f2-11e7-957a-45683388426e.png)

I suppose this is why I got troubles connecting an account thereafter.

**Comment by c-geek** [comment]
Note: restarting has no effect on this problem.

**Comment by Insoleet** [comment]
Please download 0.31.1, it is fixing this issue.
