### ISSUE TITLE
Can't add account with pubkey procedure

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#654]
After a database cleanning, I can't add my pubkey:
![capture d ecran de 2017-04-01 15-52-49](https://cloud.githubusercontent.com/assets/4758871/24579331/58e94c88-16f3-11e7-894f-deb0d2936556.png)

**Comment by M5oul** [comment]
I am using `git` version 0.31.1.
I succeed to add my wallet account.
But, as you could see upper, the member account doesn't works.

**Comment by c-geek** [comment]
Mine works.

**Comment by Insoleet** [comment]
Personally I can add your account without any problem. Seems to be a random bug, could you try again ?

**Comment by M5oul** [comment]
Fixed with 0.31.3.
