### ISSUE TITLE
0.31.0 Cannot create a new member account

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#656]
I removed my .config/sakia.

Then I started Sakia and tried to create a new member account:

![image](https://cloud.githubusercontent.com/assets/969136/24579417/7c8614c6-16f5-11e7-8a0b-a27b217ffaae.png)

But finally I get a notification error:

    UID broadcast
    Document has unknown fields or wrong line ending format

**Comment by Insoleet** [comment]
Thanks for reporting. There was indeed some problems, it will be fixed in next release.

**Comment by jpfox** [comment]
I test v 0.31.1 on debian and get this error and I don't know what to do : 

    UID broadcast
    Document has unkonw fields or wrong line ending format

More log in console : 

PyInstaller Bootloader 3.x
LOADER: executable is /opt/sakia/sakia.bin
LOADER: homepath is /opt/sakia
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /opt/sakia/sakia.bin
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /opt/sakia
LOADER: LD_LIBRARY_PATH=/opt/sakia
PyInstaller Bootloader 3.x
LOADER: executable is /opt/sakia/sakia.bin
LOADER: homepath is /opt/sakia
LOADER: _MEIPASS2 is /opt/sakia
LOADER: archivename is /opt/sakia/sakia.bin
LOADER: Already in the child - running user's code.
LOADER: Python library: /opt/sakia/libpython3.5m.so.1.0
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is /opt/sakia/base_library.zip:/opt/sakia
LOADER: sys.prefix is /opt/sakia
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is /opt/sakia/base_library.zip:/opt/sakia
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_qt5.py
LOADER: Running pyi_rth_qt5plugins.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running main.py
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc857ef0>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc737710>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc71e9b0>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7d402ffd0>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc85cbe0>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc85cbe0>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc309b38>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc290b38>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc6ba940>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc6ba940>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc6bcc50>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc286438>
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff7bc7efc18>
ERROR:root:Unclosed connection
client_connection: Connection<('g1.duniter.org', 443, True)>
ERROR:root:Unclosed response
client_response: <ClientResponse(wss://g1.duniter.org:443/ws/peer) [101 Switching Protocols]>
<CIMultiDictProxy('Server': 'nginx/1.6.2', 'Date': 'Sat, 01 Apr 2017 15:42:48 GMT', 'Connection': 'upgrade', 'Upgrade': 'websocket', 'Sec-Websocket-Accept': 'bTFoCVM4Rra7+3L/9FFRTw5EdZs=')>

ERROR:root:Unclosed connection
client_connection: Connection<('g1.duniter.org', 443, True)>
ERROR:root:Unclosed response

**Comment by Insoleet** [comment]
Haha yes, it's another problem that cgeek as revealed. Release of 0.31.2 is on the way, everything should be alright with this one ;) 

Sorry for the inconvenience.

**Comment by jpfox** [comment]
I've closed sakia, I've erased my ~/.config/sakia folder and got the same error :-(

**Comment by jpfox** [comment]
cool :-)

**Comment by jpfox** [comment]
I've installed v0.31.2 and it works :-)
Many thanks
