### ISSUE TITLE
Can't add a pubkey connection

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#659]
Seems like their is debugging code left: when I accept the license, I get this error + error messages:

![image](https://cloud.githubusercontent.com/assets/969136/24580838/eae04634-170f-11e7-9951-d654f7f57ae9.png)

**Comment by Insoleet** [comment]
Mmmmf ridiculous error. I need to add a test on the pubkey connect. Thanks for report, probably won't be fixed before next week...

**Comment by Insoleet** [comment]
Fixed in 0.31.3

**Comment by c-geek** [comment]
Yes it works now!
