### ISSUE TITLE
Error in transaction history of Remuniter

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#665]
If you add Remuniter's connection into Sakia, you might have something like this:

![image](https://cloud.githubusercontent.com/assets/969136/24669216/dda23aac-1969-11e7-92c4-181239f5d3bc.png)

I don't see why we have an output with `-1,55`. I had a look at blockchain's database, and there is only one transaction with comment `REMU:7001:7500`.

----

**Important**: if I restart, one of the movements disappears:

![image](https://cloud.githubusercontent.com/assets/969136/24669388/8f9eb3de-196a-11e7-9df3-dc8fda13cd99.png)

**Comment by M5oul** [comment]
May be linked to https://github.com/duniter/sakia/issues/636.

**Comment by Insoleet** [comment]
Can you share your g1.db file ?

**Comment by c-geek** [comment]
Yes, but 155 is what is sent to c-geek. And I'm showing you Remuniter's account.

Indeed that's what happens: Remuniter's account shows the amount spent to c-geek, not the one sent to everyone.

https://dl.cgeek.fr/jirafeau/f.php?h=3xdZQnF6

**Comment by Insoleet** [comment]
Ok so this is indeed probably linked to #636  . I'll take a look, thanks everyone.

**Comment by Insoleet** [comment]
At the moment I cannot reproduce this bug, neither for transactions or dividends. I added accounts multiple times using pubkeys, but I never reproduce the error.

Do you have some more details about how you proceeded to introduce this bug ?

**Comment by c-geek** [comment]
You need to have Sakia up with Remuniter account added when a Remuniter tx is added. Remuniter txs are added each 500 blocs.

**Comment by Insoleet** [comment]
Great, I found the cause of the bug ! It was a big one which shown multiple errors in tx history. You will have to reset sakia on next update. 

Thanks everyone for helping me on this one !

**Comment by c-geek** [comment]
I've retried with a brand new Sakia installation (and data reset), and the problem remains as there is still a bug in the Remuniter account: the displayed amounts are not the sum of outputs (25 Ğ1) but only the part given to cgeek account (probably because I have this account in Sakia):

![image](https://cloud.githubusercontent.com/assets/969136/24791566/eb71aaa6-1b7a-11e7-95ea-e84c2939c5e7.png)

You can easily reproduce this bug with the following scenario:

* add pubkey account `cgeek` + `2ny7YAdmzReQxAayyJZsyVYwYhVyax2thKcGknmQy5nQ`
* add pubkey account of Remuniter `TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS`

Here is my g1.db: https://dl.cgeek.fr/jirafeau/f.php?h=20VtBBfs

**Comment by c-geek** [comment]
It seems fixed now :-) thanks!
