### ISSUE TITLE
Bad account balance

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#667]
Ubuntu / Sakia 0.31.4

Bad account balance for pubkey 6co4yXkm3SJ7ZWoNKXBPM8CFm5nPgjQWT67mZJnivjez

It should be 50 Ğ1 (watch transactions) and Sakia displays 100 Ğ1 !?

Balance is ok in Cesium.

**Comment by M5oul** [comment]
With Silkaj, there is 50 Ğ1.
