### ISSUE TITLE
Right click doesn't works on network and transactions tabs

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#668]
Right click doesn't display the drop-down menu on network and transactions tabs.
It works on WoT tab on identities, there a drop-down menu.
May be linked to charts.

**Comment by Insoleet** [comment]
On the dev branch, both menu should work (network and transactions).

**Comment by M5oul** [comment]
I think it's a bug. It doesn't works on dev branch.

**Comment by Insoleet** [comment]
You don't have any menu at all ?

**Comment by M5oul** [comment]
Ah, in fact, it works in expert mode!
