### ISSUE TITLE
Sakia 0.31.5 lack of licence ğ1 when certifying !?

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#674]
La licence Ğ1 n'apparaît pas quand on clique sur "certification", alors qu'elle apparaît lorsqu'on veut connecter un compte. Elle devrait apparaître aussi...

A noter que l'action "certification" tout autant que l'action "envoyer de la monnaie" devraient être liées aux comptes correspondants susceptiles d'envoyer de la monnaie et de certifier et n'être donc pas des boutons de menu général.

A contrario et bizarrement les informations générales sur ğ1 et sur la monnaie ne devraient pas être liées au fait que l'on soit sur un compte, mais faire partie du menu général...

**Comment by Insoleet** [comment]
When certifying the license appears when you send the certification, and ask for confirmation. But I agree that message box dialogs are rather annoying and everything should be integrated in only one window.

For the actions, they are available in the top menu like on Thunderbird : you can select the account to use when you send the certification or the money. There is no problem here, I think.

**Comment by galuel** [comment]
A signature is made with a contract only after reading the contract. So the Licence Ğ1 should appear before asking the user to sign the certification, and not just before the "publish" action, when the signature is yet made.

**Comment by Insoleet** [comment]
Fixed in 0.32.
