### ISSUE TITLE
WoT view: pubkey displayed instead of uid

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#675]
![wot_view_pubkey_instead_of_id](https://cloud.githubusercontent.com/assets/4758871/24897045/ae5c6988-1e97-11e7-90b3-daa39587c8a1.png)

```bash
silkaj id 9kPh8rULm6ba2gDHtSRtj7ptF4ewauKse1cC8eyX3UiT
9kPh8rULm6ba2gDHtSRtj7ptF4ewauKse1cC8eyX3UiT public key corresponds to identity: OlivierAuber
```

**Comment by Insoleet** [comment]
Yes, sometimes sakia didn't find the identity for some reason (example : connection failure), and it displays the pubkey. 

If you click on your nickname, this could refresh the information.
