### ISSUE TITLE
WoT view: enlarge spaces between identity

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#676]
There is many space left, it would be more visible if there is more space betwen certifiers, the id and the certified.
Here there is almost 20 certifications each side. It will be impossible with 50~100 certifications
![wot_view_enlarge_spaces](https://cloud.githubusercontent.com/assets/4758871/24897141/0d211f04-1e98-11e7-8898-359e7526f49c.png)

**Comment by Insoleet** [comment]
The display is not the same for me ! I guess its your hidpi once again :)

**Comment by M5oul** [comment]
Ok, so let's put that for future contribution.

**Comment by M5oul** [comment]
Linked to https://github.com/duniter/sakia/issues/669

**Comment by Insoleet** [comment]
Should be better in 0.32.0RC1.

**Comment by M5oul** [comment]
Yep, it's much better thanks.
