### ISSUE TITLE
Balance is not updated on start

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#677]
On the first start of my Sakia today, I was surprised not to see my produced UD of today.

Indeed, the network seems alright to Sakia which sees the same current block as my personal node, and the UD has been produced 2 hours ago. So why is it not shown?!

![image](https://cloud.githubusercontent.com/assets/969136/24910661/bd0eeef2-1ec8-11e7-8f16-d5f12d72d93e.png)

If I wait for a new block on the network, I get the following error:

```
    An unhandled exception occured

    ----
    Traceback (most recent call last):

  File "sakia/gui/navigation/txhistory/table_model.py", line 221, in add_transfer

AttributeError: 'Transaction' object has no attribute 'issuer'
```

followed immediately by another:

```
    Exception in callback Task._wakeup(<_GatheringFu...0, ...}, ...]>)
handle: <Handle Task._wakeup(<_GatheringFu...0, ...}, ...]>)>

    ----
    Traceback (most recent call last):

  File "asyncio/events.py", line 125, in _run

  File "asyncio/tasks.py", line 307, in _wakeup

  File "asyncio/tasks.py", line 291, in _step

KeyError: <QSelectorEventLoop running=True closed=False debug=False>
```

And I still do not see my UD while a block has been added to the blockchain since the start of Sakia.

I waited a bit more, and I get these 2 errors again. But finally, I can see the UD in my transfers:

![image](https://cloud.githubusercontent.com/assets/969136/24910885/7811b568-1ec9-11e7-8aa4-de1f324e7c2c.png)

**Comment by Insoleet** [comment]
Bug of 0.31.5 already fixed.
