### ISSUE TITLE
speed up websocket 60x !

### ISSUE THREAD

**Issue by vtexier** [duniter/sakia#680]
https://www.willmcgugan.com/blog/tech/post/speeding-up-websockets-60x/
I don't known if this article can be useful,  but it mention aiohttp to speed up Web socket.

**Comment by Insoleet** [comment]
I'm glad to see you still around :) I hope everything is fine !

About this article, if I read it correctly, it mentions that aiohttp already uses a fast method for web sockets. Since Sakia is using aiohttp, I guess we are find on this one ?

**Comment by vtexier** [comment]
> I'm glad to see you still around :) I hope everything is fine !

Yes I'm still around ! I am quiet because I am tired, but I will be back one day to help again !

> Since Sakia is using aiohttp, I guess we are find on this one ?

Alright then ! I close it.
