### ISSUE TITLE
sakia 0.31.6 - sakia is already running

### ISSUE THREAD

**Issue by chaica** [duniter/sakia#682]
Linux Debian Stretch
Sakia 0.31.6

Each time sakia does not shut properly, the next time I launch a popup appears and tells: sakia is already running. I do have to relaunch again in order to launch sakia normally.

It would be great if the message was : "sakia was not shut down properly, fixing and launching now"
or something alike but that sakia is launched anyway because it is counter productive to have to relaunch two times in order to have sakia working properly after a crash

**Comment by Insoleet** [comment]
Fixed in 0.32.
