### ISSUE TITLE
Sakia - Bug - Erreur de connexion 

### ISSUE THREAD

**Issue by Yioshiz** [duniter/sakia#691]
Bonjour,
Voici quelques bugs de connexion sous Sakia et sous Linux Mint 18.1:
Tout d'abord, ayant déjà un compte "Non membre", j'essaie de me connecter sous Sakia au lieu de Césium, je vais sur "Connect with an existing identidy"
https://moul.re/jirafeau/f.php?h=0jTAv7iC&p=1

Ensuite, il y a la licence qui apparaît, j'accpete, ce qui m'emmène à cette interface:
https://moul.re/jirafeau/f.php?h=2s6o-jHR&p=1
Déjà, je ne comprends pas pourquoi, il me demande 2 fois les pass phrase et mot de passe alors que ce n'est pas une création de compte, donc je quitte l'application pour revenir en arrière et cela m'afficher des erreurs:
https://moul.re/jirafeau/f.php?h=0DdVTJGD&p=1

Voici les codes d'erreur 1:
```
 An unhandled exception occured

    ----
    Traceback (most recent call last):

  File "sakia/gui/navigation/network/table_model.py", line 90, in data

  File "sakia/data/processors/blockchain.py", line 51, in adjusted_ts

  File "sakia/data/processors/blockchain.py", line 88, in parameters

AttributeError: 'NoneType' object has no attribute 'parameters'
```
Ensuite l'autre bug qui apparait sans arrêt:
 ```
Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f98e8294a58>

    ----
```
Du coup, je ne peux que visualiser avec "Connect with a public Key" Mais je n'ai pas besoin de mettre pass phrase et mot de passe.
https://moul.re/jirafeau/f.php?h=0-BMIdAe&p=1

C'est comme si la connexion avec un compte existant n'est pas accessible.

Suite à la connexion avec " Connect with a public Key", les bugs d'auparavant n'affichent plus lorsque je ferme le programme mais je ne trouve toujours pas le moyen de me connecter avec la pass phrase et mot de passe.

**Comment by Insoleet** [comment]
Ce bug sera corrigé dans la 0.32. Merci pour le report ! 

Je vais release la 0.32.0RC4 dans la journée, tu pourras vérifier la correction du bug :)
