### ISSUE TITLE
Certification process bugs/enh

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#694]
I discovered that certification button is no more here.
The only solution is to `Search an identity`.
It's kind of buggy since a long time to found someone. I have to click many time to found someone.
Then, right click `Certify Identity`. The window open, but, it's pubkey it's not added…

Finally, I add the pubkey back and finally, I can't click on `Please select an identity`. Why?

Finally, I don't know how to certify an identity.

**Comment by Insoleet** [comment]
You have to click on your identity in the left panel, the certification button has been moved here.

> It's kind of buggy since a long time to found someone. I have to click many time to found someone.

That's the time needed to lookup enough nodes on the network to be certain about displayed informations, sadly.

>  Then, right click Certify Identity. The window open, but, it's pubkey it's not added…

That's a bug.

> Finally, I add the pubkey back and finally, I can't click on Please select an identity. Why?

It seems to be a bug too.

**Comment by M5oul** [comment]
> You have to click on your identity in the left panel, the certification button has been moved here.

Ok, saw.

> That's the time needed to lookup enough nodes on the network to be certain about displayed informations, sadly.

Ok, it's a choice. Security over speed.

**Comment by M5oul** [comment]
> You have to click on your identity in the left panel, the certification button has been moved here.

Certification process works fine using this view. It does not work on the window view.
I think, the window view could be removed.
