### ISSUE TITLE
critical error 1

### ISSUE THREAD

**Issue by PaulFree14** [duniter/sakia#704]
When starting sakia I resieve several "critical errors". This is the first:
.  

> "A critical error occured. Select the details to display it. Please report it to the developers github" 

 

>    An unhandled exception occured
> 
>     ----
>     Traceback (most recent call last):
> 
>   File "sakia/main.py", line 112, in <module>
> 
>   File "site-packages/quamash/__init__.py", line 266, in run_until_complete
> 
>   File "asyncio/futures.py", line 274, in result
> 
>   File "asyncio/tasks.py", line 239, in _step
> 
>   File "sakia/app.py", line 160, in initialize_blockchain
> 
>   File "sakia/data/processors/blockchain.py", line 308, in initialize_blockchain
> 
>   File "sakia/data/repositories/blockchains.py", line 21, in insert
> 
>   File "site-packages/attr/filters.py", line 47, in exclude
> 
>   File "site-packages/attr/filters.py", line 17, in _split_what
> 
>   File "site-packages/attr/_make.py", line 435, in hash_
> 
> TypeError: unhashable type: 'BlockchainParameters'
> 

I'm using arch linux. I installed sakia via `yaourt sakia` and choosed this package: 

> "1 aur/sakia 0.32.0RC1-1" 

My system is fresh updated via `yaourt -Syu` but still I resieved while intalling following: 

> You are using pip version 8.1.1, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command

I just continued the installing process.

**Comment by Insoleet** [comment]
Yes this is a bug that I fixed yesterday, caused by a backward-incompatible change in the https://github.com/python-attrs/attrs/ library. I'll publish a fix today.
