### ISSUE TITLE
critical error 2. 

### ISSUE THREAD

**Issue by PaulFree14** [duniter/sakia#705]
When starting sakia I resieve several "critical errors". 

1. issue here: https://github.com/duniter/sakia/issues/704

This is the secound: 

```
    Task was destroyed but it is pending!
task: <Task pending coro=<NetworkService.discovery_loop() running at sakia/services/network.py:169> wait_for=<Future pending cb=[Task._wakeup()]>>

    ----
    
```

**Comment by Insoleet** [comment]
This is probably caused by your first crash, which kills the event loop and provoks multiples errors in a row.
