### ISSUE TITLE
Crash au lancement: debian 8

### ISSUE THREAD

**Issue by pirboazo** [duniter/sakia#714]
Hello,

Voici le message reçu dans l'interface.

    Task was destroyed but it is pending!
task: <Task pending coro=<NetworkService.discovery_loop() running at sakia/services/network.py:179> wait_for=<Future pending cb=[Task._wakeup()]>>

    ----

Pierre

**Comment by Insoleet** [comment]
Bonjour et merci pour le rapport de bug !

Quelle version de sakia utilisez vous ?

**Comment by Insoleet** [comment]
Pas de réponse depuis 25 jours, je ferme le ticket.

**Comment by pirboazo** [comment]
Désolé mais n'ayant pas vu votre commentaire je suis passé sur césium.

De plus j'ai upgradé ma machine en stretch donc impossibe de vous redonner de l'info.
Je tenterai ce week-end de faire une installation sous debian 9.

A+
Pierre
