### ISSUE TITLE
duplicate oneself tx

### ISSUE THREAD

**Issue by librelois** [duniter/sakia#715]
When a compress source tx is send to oneself (for send big amout after), the tx is duplicate in transfers view : 

![sakia-issue-53](https://user-images.githubusercontent.com/22670546/27110871-8f651efc-50ac-11e7-9c6c-42c9a5384f5c.png)

**Comment by Insoleet** [comment]
Can you share your g1.db file please ?

**Comment by librelois** [comment]
https://framadrop.org/r/PoNr-w_buj#4G+2upDLxK0ue+3aAobR405QoiTUp9G9dZiXtNCKv+Q=

**Comment by Insoleet** [comment]
Which version are you using ? With latest one ( 0.32.0RC6 ) the display is correct : 

![image](https://user-images.githubusercontent.com/1170293/27192080-4d14ebbe-51fa-11e7-9138-41f04bb0247d.png)

**Comment by librelois** [comment]
0.32.0RC2

**Comment by Insoleet** [comment]
You should upgrade ;)

**Comment by librelois** [comment]
yes, it's work with 0.32.0RC6 :)
