### ISSUE TITLE
PermissionError pour Windows 64 bits

### ISSUE THREAD

**Issue by mcl12345** [duniter/sakia#725]
An unhandled exception occured

    ----
    Traceback (most recent call last):

  File "sakia\main.py", line 100, in <module>

  File "sakia\app.py", line 85, in startup

  File "sakia\options.py", line 35, in from_arguments

  File "os.py", line 241, in makedirs

PermissionError: [WinError 5] Accès refusé: 'C:\\Windows\\system32\\config\\systemprofile\\.config\\sakia'

**Comment by Insoleet** [comment]
Wow, weird bug.

Can you open a powershell terminal and run : 

```
echo $env:HOME
echo $env:APPDATA
```

Thanks !

**Comment by mcl12345** [comment]
It displays $env:HOME and $env:APPDATA

**Comment by Insoleet** [comment]
Did you open a powershell terminal or a cmd terminal ?

**Comment by mcl12345** [comment]
this one : 
http://hpics.li/37e480e

**Comment by mcl12345** [comment]
echo $env:HOME
>  C:\Windows\system32\config\systemprofile

echo $env:APPDATA
C:\User\morvan\AppData\Roaming
