### ISSUE TITLE
Build sakia

### ISSUE THREAD

**Issue by mcl12345** [duniter/sakia#726]
How to build sakia ?
I tried :
Build scripts
> Run python3 gen_resources.py in sakia folder
> Run python3 gen_translations.py in sakia folder
> Run python3 setup.py build in sakia folder

The executable is generated in "build" folder, named "sakia"

But I didn't find the folder "build"

So I tried another way , with "cd src / sakia" and :
> python main.py

But It doesn't work

**Comment by mcl12345** [comment]
Traceback (most recent call last):
  File "sakia/main.py", line 14, in <module>
    from sakia.app import Application
  File "/home/sb/deve/duniter_project/htmlless_explorer/sakia/src/sakia/app.py", line 11, in <module>
    from sakia.services import NetworkService, BlockchainService, IdentitiesService, \
  File "/home/sb/deve/duniter_project/htmlless_explorer/sakia/src/sakia/services/__init__.py", line 4, in <module>
    from .documents import DocumentsService
  File "/home/sb/deve/duniter_project/htmlless_explorer/sakia/src/sakia/services/documents.py", line 14, in <module>
    from sakia.data.processors import BlockchainProcessor, IdentitiesProcessor, NodesProcessor, \
  File "/home/sb/deve/duniter_project/htmlless_explorer/sakia/src/sakia/data/processors/__init__.py", line 1, in <module>
    from .nodes import NodesProcessor
  File "/home/sb/deve/duniter_project/htmlless_explorer/sakia/src/sakia/data/processors/nodes.py", line 2, in <module>
    import sqlite3
  File "/home/sb/.pyenv/versions/3.5.0/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/sb/.pyenv/versions/3.5.0/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'

When I try : cd src && python sakia/main.py at the end of the guide

**Comment by vtexier** [comment]
I think that your Pyenv install is not complete. 
You need the sqllite dev lib before installing Python.

https://github.com/duniter/sakia/blob/master/doc/install_for_developers.md#build-python-353

**Comment by mcl12345** [comment]
Yes I did 
the only problem I encountered is with
> PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.5.3
pyenv shell 3.5.3

**Comment by mcl12345** [comment]
and I tried to build sakia on Windows 64 , but I can't find the  Conda console .

**Comment by Insoleet** [comment]
> where the build failed

Any log maybe ?

**Comment by mcl12345** [comment]
sb@sb-N550JV:~$ PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.5.3
python-build: definition not found: 3.5.3

See all available versions with `pyenv install --list'.

If the version you need is missing, try upgrading pyenv:

  cd /home/sb/.pyenv/plugins/python-build/../.. && git pull && cd -
sb@sb-N550JV:~$ pyenv shell 3.5.3
pyenv: version `3.5.3' not installed
sb@sb-N550JV:~$ pyenv install --list
Available versions:
  2.1.3
  2.2.3
  2.3.7
  2.4
  2.4.1
  2.4.2
  2.4.3
  2.4.4
  2.4.5
  2.4.6
  2.5
  2.5.1
  2.5.2
  2.5.3
  2.5.4
  2.5.5
  2.5.6
  2.6.6
  2.6.7
  2.6.8
  2.6.9
  2.7-dev
  2.7
  2.7.1
  2.7.2
  2.7.3
  2.7.4
  2.7.5
  2.7.6
  2.7.7
  2.7.8
  2.7.9
  2.7.10
  2.7.11
  2.7.11rc1
  3.0.1
  3.1
  3.1.1
  3.1.2
  3.1.3
  3.1.4
  3.1.5
  3.2-dev
  3.2
  3.2.1
  3.2.2
  3.2.3
  3.2.4
  3.2.5
  3.2.6
  3.3.0
  3.3-dev
  3.3.1
  3.3.2
  3.3.3
  3.3.4
  3.3.5
  3.3.6
  3.4.0
  3.4-dev
  3.4.1
  3.4.2
  3.4.3
  3.5.0
  3.5-dev
  3.6-dev
  anaconda-1.4.0
  anaconda-1.5.0
  anaconda-1.5.1
  anaconda-1.6.0
  anaconda-1.6.1
  anaconda-1.7.0
  anaconda-1.8.0
  anaconda-1.9.0
  anaconda-1.9.1
  anaconda-1.9.2
  anaconda-2.0.0
  anaconda-2.0.1
  anaconda-2.1.0
  anaconda-2.2.0
  anaconda-2.3.0
  anaconda-2.4.0
  anaconda3-2.0.0
  anaconda3-2.0.1
  anaconda3-2.1.0
  anaconda3-2.2.0
  anaconda3-2.3.0
  anaconda3-2.4.0
  ironpython-dev
  ironpython-2.7.4
  ironpython-2.7.5
  jython-dev
  jython-2.5.0
  jython-2.5-dev
  jython-2.5.1
  jython-2.5.2
  jython-2.5.3
  jython-2.5.4-rc1
  jython-2.7.0
  jython-2.7.1b1
  jython-2.7.1b2
  miniconda-2.2.2
  miniconda-3.0.0
  miniconda-3.0.4
  miniconda-3.0.5
  miniconda-3.3.0
  miniconda-3.4.2
  miniconda-3.7.0
  miniconda-3.8.3
  miniconda-3.9.1
  miniconda-3.10.1
  miniconda-3.16.0
  miniconda-3.18.3
  miniconda3-2.2.2
  miniconda3-3.0.0
  miniconda3-3.0.4
  miniconda3-3.0.5
  miniconda3-3.3.0
  miniconda3-3.4.2
  miniconda3-3.7.0
  miniconda3-3.8.3
  miniconda3-3.9.1
  miniconda3-3.10.1
  miniconda3-3.16.0
  miniconda3-3.18.3
  pypy-c-jit-latest
  pypy-c-nojit-latest
  pypy-dev
  pypy-stm-2.3
  pypy-portable-2.3.1
  pypy-portable-2.4
  pypy-portable-2.5
  pypy-portable-2.5.1
  pypy-stm-2.5.1
  pypy-portable-2.6
  pypy-portable-2.6.1
  pypy-portable-4.0
  pypy-portable-4.0.1
  pypy-1.5-src
  pypy-1.5
  pypy-1.6
  pypy-1.7-dev
  pypy-1.7
  pypy-1.8-dev
  pypy-1.8
  pypy-1.9-dev
  pypy-1.9
  pypy-2.0-dev
  pypy-2.0-src
  pypy-2.0
  pypy-2.0.1-src
  pypy-2.0.1
  pypy-2.0.2-src
  pypy-2.0.2
  pypy-2.1-src
  pypy-2.1
  pypy-2.2-src
  pypy-2.2
  pypy-2.2.1-src
  pypy-2.2.1
  pypy-2.3-src
  pypy-2.3
  pypy-2.3.1-src
  pypy-2.3.1
  pypy-2.4.0-src
  pypy-2.4.0
  pypy-2.4-beta1-src
  pypy-2.4-beta1
  pypy-2.5.0-src
  pypy-2.5.0
  pypy-2.5.1-src
  pypy-2.5.1
  pypy-2.6.0-src
  pypy-2.6.0
  pypy-2.6.1-src
  pypy-2.6.1
  pypy-4.0.0-src
  pypy-4.0.0
  pypy-4.0.1-src
  pypy-4.0.1
  pypy3-dev
  pypy3-portable-2.3.1
  pypy3-portable-2.4
  pypy3-2.3.1-src
  pypy3-2.3.1
  pypy3-2.4.0-src
  pypy3-2.4.0
  stackless-dev
  stackless-2.7-dev
  stackless-2.7.2
  stackless-2.7.3
  stackless-2.7.4
  stackless-2.7.5
  stackless-2.7.6
  stackless-2.7.7
  stackless-2.7.8
  stackless-3.2-dev
  stackless-3.2.2
  stackless-3.2.5
  stackless-3.3-dev
  stackless-3.3.5
  stackless-3.4.1
sb@sb-N550JV:~$ PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.4.1
Downloading Python-3.4.1.tgz...
-> https://www.python.org/ftp/python/3.4.1/Python-3.4.1.tgz
Installing Python-3.4.1...
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/yyuu/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 16.04 using python-build 20151124-8-gaaec358)

Inspect or clean up the working tree at /tmp/python-build.20170828232810.8272
Results logged to /tmp/python-build.20170828232810.8272.log

Last 10 log lines:
(cd /home/sb/.pyenv/versions/3.4.1/share/man/man1; ln -s python3.4.1 python3.1)
if test "xupgrade" != "xno"  ; then \
	case upgrade in \
		upgrade) ensurepip="--upgrade" ;; \
		install|*) ensurepip="" ;; \
	esac; \
	LD_LIBRARY_PATH=/tmp/python-build.20170828232810.8272/Python-3.4.1 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Ignoring ensurepip failure: pip 1.5.6 requires SSL/TLS

**Comment by Insoleet** [comment]
I think you need to do this : 

```
cd ~/.pyenv
git pull
```

Then install the ubuntu packages : 
```
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev
```

And then starts again ```PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.5.3```

**Comment by mcl12345** [comment]
incroyable , ça fonctionne
