### ISSUE TITLE
Error SSL transport

### ISSUE THREAD

**Issue by mcl12345** [duniter/sakia#729]
This error did not force me to restart the application

     Fatal error on SSL transport
     protocol: <asyncio.sslproto.SSLProtocol object at 0x000000001382DCF8>
     transport: <_SelectorSocketTransport closing fd=1616 read=idle write=<idle, bufsize=0>>

    ----
    Traceback (most recent call last):

    File "asyncio\sslproto.py", line 637, in _process_write_backlog

    AttributeError: 'NoneType' object has no attribute 'feed_appdata'

**Comment by brycedrennan** [comment]
I have received this error on a completely unrelated project.  I haven't yet figured out the cause. Could be a bug in sslproto or the result of some malformed https.

**Comment by Insoleet** [comment]
It seems to be related to ClientSession badly closed. Since I fixed this link in Sakia, I canno't reproduce this error anymore.
