### ISSUE TITLE
Error on socket transport

### ISSUE THREAD

**Issue by mcl12345** [duniter/sakia#730]
This error did not force me to restart the application

    Fatal read error on socket transport
    protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb88f80ee80>
    transport: <_SelectorSocketTransport fd=67 read=polling write=<idle, bufsize=0>>

     ----
     Traceback (most recent call last):

    File "/home/sb/.pyenv/versions/3.5.3/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
     data = self._sock.recv(self.max_size)

         OSError: [Errno 22] Argument invalide

**Comment by Insoleet** [comment]
Not enough information.
