### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by Nartagnan** [duniter/sakia#731]
I tried to send a transaction with 0Ğ1 by mistake.
Just after that, I quit Sakia, relaunched it and resent the same transaction with 500Ğ1 and I got this message :
> Task exception was never retrieved
future: <Task finished coro=<accept() done, defined at sakia/gui/sub/transfer/controller.py:173> exception=AttributeError("'NoneType' object has no attribute 'state'",)>
    ----
    Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/sub/transfer/controller.py", line 191, in accept
  File "sakia/gui/sub/transfer/model.py", line 101, in send_money
  File "sakia/services/transactions.py", line 47, in parse_sent_transaction
AttributeError: 'NoneType' object has no attribute 'state'

I had to quit again, and now I have :
![bug2](https://user-images.githubusercontent.com/29802590/30390019-01ccb3c4-98b5-11e7-9ef4-05f27e1d3528.png)
-100Ğ1 is another thing, but the amount of 390 do not correspond to anything.

**Comment by Insoleet** [comment]
Can you share your g1.db file ? It should be in `~/.config/sakia/Default Profile` folder on Linux, or `%APPDATA%\sakia\Default Profile` on Windows.

The -390 transactions are chained (Sakia merged your units of money to be able to send the 500 units document). Still, they seems weird (Why so much 390 number ?). Also, if the problem persist, just delete your connection from Sakia and add it back.

**Comment by Insoleet** [comment]
This should be correctly handled in latest release.
