### ISSUE TITLE
Fress install 0.32.2 on Xubuntu 17.04 : 100% during 20 minutes ?

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#736]
Quand on se connecte la première fois, on arrive en passant par Cesium à récupérer une pubkey ou ID via l'annuaire (qui existe pourtant dans Sakia, mais on ne peut pas y accéder, on a une fenêtre qui nous demande un compte), et alors on charge un compte dans Sakia.

Commence alors une synchro qui va durer... une plombe !

La barre de chargement arrive vite à 100% alors qu'il reste des milliers de blocs à charger, le tout prenant 10, 15 ou 20 minutes... Ce fonctionnement est erroné, une barre de chargement ne doit pas montrer un % de (nombre de blocs chargés) / (nombre total) car elle va converger très rapidement vers 100% alors qu'il va rester beaucoup de temps pour la syncrho !

Le fonctionnement normal de la barre de chargement est de donner le % temporel réalisé estimé, et le temps restant estimé (voir à ce sujet Qbittorrent et ses champs d'information concernant le chargement d'un fichier).

Le temps restant estimé se calculant simplement par : nbre de blocs restant à charger * temps moyen de chargement d'un bloc = (nbre total de blocs - n° bloc actuel) * (heure actuelle - heure de début de chargement) / n° de bloc actuel

Que l'on peut calculer / mettre à jour toutes les 10 secondes par exemple.

**Comment by Insoleet** [comment]
Fixed in latest release.
