### ISSUE TITLE
"Connect a wallet" does not control the fields

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#737]
In this window, I can type 4 different values and Sakia will accept the creation of the wallet.

![image](https://user-images.githubusercontent.com/969136/31437234-d9315434-ae84-11e7-8d49-20906adfef61.png)

**Comment by Insoleet** [comment]
Good catch. Fixed in https://github.com/duniter/sakia/commit/2b6103966639a0b5ddaa6d25d8d4a960e9d306f8
