### ISSUE TITLE
Trouble with dark theme

### ISSUE THREAD

**Issue by aeris** [duniter/sakia#738]
With system dark theme, network list is unreadable.

![screenshot_20171013_205802](https://user-images.githubusercontent.com/51246/31565733-7d450a2e-b057-11e7-8a1c-583f89e2b222.png)

I try to create a patch to force the foreground color to black [here](https://github.com/duniter/sakia/blob/master/src/sakia/gui/navigation/network/table_model.py#L275-L276) but it seems it doesn't work (still the system foreground despite the hardcoded color).

**Comment by Insoleet** [comment]
In 0.32.3, you'll have the possibility to enable dark theme compatibility : 

![image](https://user-images.githubusercontent.com/1170293/31862681-37d5be4c-b742-11e7-8b3f-9abadded20fb.png)
