### ISSUE TITLE
Crash after the first launching

### ISSUE THREAD

**Issue by mcl12345** [duniter/sakia#750]
https://drive.google.com/open?id=0BxLp8QADQWfBQWdZSnc5MDhXMnc

**Comment by Insoleet** [comment]
In your install folder, what happens if you copy the folder 

```
[sakia_install_dir]\PyQt5\Qt\plugins
```

To

```
[sakia_install_dir]\qt5_plugins
```

**Comment by urodelus** [comment]
Hello Inso, I've got the same problem and moving the folder `...\PyQt5\Qt\plugins` in `...\qt5_plugins\` don't change anything.

**Comment by Insoleet** [comment]
It seems to be a bug of pyinstaller 3.3 : https://github.com/pyinstaller/pyinstaller/issues/2857

I'll go back to 3.2 version for next release.
