### ISSUE TITLE
Incohérence solde de compte Sakia / Cesium

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#763]
![sans titre](https://user-images.githubusercontent.com/5245398/33479940-43b2adbc-d68f-11e7-8c0b-5f33bb70977c.jpg)

**Comment by galuel** [comment]
![silkaj](https://user-images.githubusercontent.com/5245398/33481884-c7210322-d696-11e7-87da-558b4a8771b0.jpg)

Silkaj semble confirmer que Cesium a bon...

**Comment by Insoleet** [comment]
Peux-tu lancer Sakia dans un profil temporaire : 

```
sakia --profile test
```

Ajouter ton compte à ce profil et regarder le résultat du solde ?

**Comment by galuel** [comment]
Pareil... Solde incohérent.

![sakia](https://user-images.githubusercontent.com/5245398/33655913-c5d52c32-da74-11e7-9d0f-b641a1b028bd.jpg)

**Comment by Insoleet** [comment]
Bizarre, je vais regarder ça.
