### ISSUE TITLE
Client / Serveur !?

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#767]
Vite analysé Sakia refait toute une partie qui est en fait réalisée par un noeud (non-membre ou membre), à savoir récupérer les blocks pour réaliser une BDD...

Or cela me semble lourd. On devrait pouvoir associer Sakia à un noeud de confiance (possiblement sur la même machine, par défaut), et ainsi avoir accès directement à la BDD associée, sans avoir à refaire le travail fait par un noeud.

**Comment by Insoleet** [comment]
> Vite analysé Sakia refait toute une partie qui est en fait réalisée par un noeud (non-membre ou membre), à savoir récupérer les blocks pour réaliser une BDD...

C'est une limitation des API existantes : 
 - Pas de possibilité de recevoir la liste des destruction de monnaie 
 - Pas de possibilité de recevoir l'historique complet des DU et leur temps d'émission 

Sakia a pour objet d'être décentralisé totalement. C'est d'abord à traiter sous la forme d'une API. https://forum.duniter.org/t/simplified-verification-api/3631

**Comment by galuel** [comment]
Mais un noeud Duniter lui-même est de facto construit pour dialoguer avec tous les noeuds, et donc de manière décentralisée.

Donc pourquoi refaire ce que le noeud est déjà censé faire ?

**Comment by Insoleet** [comment]
Sakia n'est pas censé reparcourir la blockchain comme aujourd'hui. C'est une limitation de l'API. A terme, ça doit disparaitre, et Sakia se comportera comme un client décentralisé, pas besoin de noeud de confiance.

**Comment by galuel** [comment]
bon :)
