### ISSUE TITLE
Preference panel

### ISSUE THREAD

**Issue by Letiteuf55** [duniter/sakia#776]
Hi,
i think, it would be good to add label under all of big buttons in the Preference panel.

Also, change the icon :
- General settings -> the cursor is not mandatory
- Network settings -> a RJ45 would be more figurative instead of a power cable.

**Comment by Insoleet** [comment]
Ok, will be in 0.32.9

**Comment by Letiteuf55** [comment]
label display and General are interchanged

**Comment by Insoleet** [comment]
Erf ... Fixed in next release :)
