### ISSUE TITLE
Sakia Linux 

### ISSUE THREAD

**Issue by mcl12345** [duniter/sakia#779]
Sakia démarre que quelques secondes avec le logo dans la barre des tâches et mais pas d'interface graphique et puis il quitte.

Je l'ai installé via .deb via la logithèque

Je suis en Ubuntu 64 bits

**Comment by Insoleet** [comment]
Par la console en mode debug, tu as des logs ?

**Comment by Insoleet** [comment]
Ok its a duplicate of : https://github.com/duniter/sakia/issues/768
